SSElegant_Rooms_MapScripts::
	.byte 0


SSElegant_Rooms_Gabrielle::
# 14 "data//maps/SSElegant_Rooms/scripts.pory"
	msgbox SSElegant_Rooms_Gabrielle_Text_0, MSGBOX_NPC
	end


SSElegant_Rooms_Zoroark::
# 18 "data//maps/SSElegant_Rooms/scripts.pory"
	playmoncry SPECIES_ZOROARK_HISUI, CRY_MODE_NORMAL
# 19 "data//maps/SSElegant_Rooms/scripts.pory"
	msgbox SSElegant_Rooms_Gabrielle_Text_0, MSGBOX_NPC
	end


SSElegant_Rooms_Breech::
# 25 "data//maps/SSElegant_Rooms/scripts.pory"
	msgbox SSElegant_Rooms_Gabrielle_Text_0, MSGBOX_NPC
	end


SSElegant_Rooms_Clefable::
# 30 "data//maps/SSElegant_Rooms/scripts.pory"
	playmoncry SPECIES_CLEFABLE, CRY_MODE_NORMAL
# 31 "data//maps/SSElegant_Rooms/scripts.pory"
	msgbox SSElegant_Rooms_Gabrielle_Text_0, MSGBOX_NPC
	end


SSElegant_Rooms_NPC1::
# 37 "data//maps/SSElegant_Rooms/scripts.pory"
	msgbox SSElegant_Rooms_Gabrielle_Text_0, MSGBOX_NPC
	end


SSElegant_Rooms_NPC2::
# 41 "data//maps/SSElegant_Rooms/scripts.pory"
	msgbox SSElegant_Rooms_Gabrielle_Text_0, MSGBOX_NPC
	end


SSElegant_Rooms_Weezing::
# 45 "data//maps/SSElegant_Rooms/scripts.pory"
	playmoncry SPECIES_WEEZING_GALAR, CRY_MODE_NORMAL
# 46 "data//maps/SSElegant_Rooms/scripts.pory"
	msgbox SSElegant_Rooms_Gabrielle_Text_0, MSGBOX_NPC
	end


SSElegant_Rooms_NPC3::
# 52 "data//maps/SSElegant_Rooms/scripts.pory"
	msgbox SSElegant_Rooms_Gabrielle_Text_0, MSGBOX_NPC
	end


SSElegant_Rooms_Smeargle::
# 56 "data//maps/SSElegant_Rooms/scripts.pory"
	playmoncry SPECIES_SMEARGLE, CRY_MODE_NORMAL
# 57 "data//maps/SSElegant_Rooms/scripts.pory"
	msgbox SSElegant_Rooms_Gabrielle_Text_0, MSGBOX_NPC
	end


SSElegant_Rooms_Gabrielle_Text_0:
# 14 "data//maps/SSElegant_Rooms/scripts.pory"
	.string "$"
