#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#include "constants/battle_partner.h"

//Route 1 Trainers
#define TRAINER_NONE                          0
#define TRAINER_ROUTE1_A                      1
#define TRAINER_ROUTE1_B                      2
#define TRAINER_ROUTE1_C                      3
#define TRAINER_KOHLA_LAB                     4

//Route 3 Trainers
#define TRAINER_ROUTE3_JANA                   5 
#define TRAINER_ROUTE3_KIM                    6
#define TRAINER_ROUTE3_RONNIE                 7
#define TRAINER_ROUTE3_CHARA                  8
    //Evil team grunt
    #define TRAINER_ROUTE3_EVIL_GABRIELLE     9

//Gastree City Gym    
#define TRAINER_GASTREEGYM_JACO               10
#define TRAINER_GASTREEGYM_SKIP               11
#define TRAINER_GASTREEGYM_LEADER             12
#define TRAINER_GASTREE_KOHLA                 13

//Route 4 Evil Encounter
#define TRAINER_ROUTE4_GRUNTS                 14

//Mt. Ceram Base Camp Evil Encounter
#define TRAINER_CERAMBASECAMP_EVIL_GABRIELLE  15
#define TRAINER_CERAMBASECAMP_GRUNT1          16
#define TRAINER_CERAMBASECAMP_GRUNT2          17
#define TRAINER_CERAMBASECAMP_GRUNT3          18

//Route 4 Trainers
    //regular
    #define TRAINER_ROUTE4_RAHA               19
    #define TRAINER_ROUTE4_CAMMY              20
    #define TRAINER_ROUTE4_SONA               21
    #define TRAINER_ROUTE4_JENNY              22

//Ninja kids
    #define TRAINER_ROUTE4_KID1               23
    #define TRAINER_ROUTE4_KID2               24
    #define TRAINER_ROUTE4_KID3               25

//Base camp trainers and leader
#define TRAINER_CERAMBASECAMPGYM_A            26
#define TRAINER_CERAMBASECAMPGYM_B            27
#define TRAINER_CERAMBASECAMPGYM_C            28
#define TRAINER_CERAMBASECAMPGYM_D            29
#define TRAINER_CERAMBASECAMPGYM_LEADER       30

//Ceram
    //Trainers
    #define TRAINER_MTCERAM_A                 31
    #define TRAINER_MTCERAM_B                 32
    #define TRAINER_MTCERAM_C                 33
    #define TRAINER_MTCERAM_D                 34
    //Somber
    #define TRAINER_MTCERAM_GRUNT1            35
    #define TRAINER_MTCERAM_GRUNT2            36
    #define TRAINER_MTCERAM_GRUNT_DOUBLE      37
    //Boss battle at peak
    #define TRAINER_CERAMPEAK_MOXIE           38

//Galecrest
#define TRAINER_GALECREST_ROBBER             39
#define TRAINER_GALECREST_DETECTIVE_A        40
#define TRAINER_GALECREST_B                  41
#define TRAINER_GALECRESTGYM_A               42
#define TRAINER_GALECRESTGYM_B               43
#define TRAINER_GALECRESTGYM_C               44
#define TRAINER_GALECRESTGYM_LEADER          45

//Vilethorn Woods
#define TRAINER_VILETHORN_A                  46
#define TRAINER_VILETHORN_B                  47
#define TRAINER_VILETHORN_C                  48
#define TRAINER_VILETHORN_D                  49
#define TRAINER_VILETHORN_E                  50
#define TRAINER_VILETHORN_F                  51
#define TRAINER_VILETHORN_G                  52
#define TRAINER_VILETHORN_H                  53

//Vilethorn Mansion
#define TRAINER_VILETHORN_I                  54
#define TRAINER_GABBY_AND_TY_5               55
#define TRAINER_GABBY_AND_TY_6               56

//Route 5
#define TRAINER_ROUTE5_A                     57
#define TRAINER_ROUTE5_B                     58
#define TRAINER_ROUTE5_C                     59
#define TRAINER_ROUTE5_D                     60

//Silversun Sewers
#define TRAINER_SEWERS_A                     61
#define TRAINER_SEWERS_B                     62
#define TRAINER_SEWERS_C                     63
        #define TRAINER_SEWERS_D                     64 //unused
        #define TRAINER_SEWERS_E                     65 //unused

//Silversun Gym
#define TRAINER_SILVERSUNGYM_A               66
#define TRAINER_SILVERSUNGYM_B               67
#define TRAINER_SILVERSUNGYM_C               68
#define TRAINER_SILVERSUNGYM_D               69
#define TRAINER_SILVERSUNGYM_LEADER          70

//Two battles in the theater (one beauty and one maniac)
        #define TRAINER_THEATER_A                    71 //unused
#define TRAINER_THEATER_B                    72 

//Team Somber HQ
    #define TRAINER_SOMBERHQ_A               73
    #define TRAINER_SOMBERHQ_B               74
    #define TRAINER_SOMBERHQ_C               75
    #define TRAINER_SOMBERHQ_D               76
    #define TRAINER_SOMBERHQ_E               77
    #define TRAINER_SOMBERHQ_F               78
    #define TRAINER_SOMBERHQ_G               79
    #define TRAINER_SOMBERHQ_H               80
    #define TRAINER_SOMBERHQ_MELEA           81

//Route 6 Kohla encounter
#define TRAINER_ROUTE6_KOHLA                 82

//Route 6 Trainers
#define TRAINER_ROUTE6_A                     83
#define TRAINER_ROUTE6_B                     84
#define TRAINER_ROUTE6_C                     85
#define TRAINER_ROUTE6_D                     86
#define TRAINER_ROUTE6_E                     87
#define TRAINER_ROUTE6_F                     88
#define TRAINER_ROUTE6_G                     89
#define TRAINER_ROUTE6_H                     90
#define TRAINER_ROUTE6_I                     91
#define TRAINER_ROUTE6_J                     92
#define TRAINER_ROUTE6_K                     93

//Route 6 Gabrielle double battle
#define TRAINER_ROUTE6_GRUNT1                94
#define TRAINER_ROUTE6_GRUNT2                95
#define TRAINER_ROUTE6_GAB                   96

//Pelluca random trainer
#define TRAINER_SHANNON                      97

//Mirroh Base Camp
#define TRAINER_MIRROHBASECAMP_KOHLA         98
#define TRAINER_MIRROHBASECAMP_LEADER        99

//TRAINER_NONE
//Mt Mirroh Exterior
#define TRAINER_MIRROHEXT_A                    100
#define TRAINER_MIRROHEXT_B                    101
#define TRAINER_MIRROHEXT_C                    102
#define TRAINER_MIRROHEXT_D                    103
#define TRAINER_MIRROHEXT_E                    104
#define TRAINER_MIRROHEXT_F                    105
#define TRAINER_MIRROHEXT_G                    106
#define TRAINER_MIRROHEXT_H                    107

//Mt Mirroh Interior
    //1F
    #define TRAINER_MIRROHINT_A                   108
    #define TRAINER_MIRROHINT_B                   109
    #define TRAINER_MIRROHINT_C                   110
    #define TRAINER_MIRROHINT_D                   111
    #define TRAINER_MIRROHINT_E                   112
    #define TRAINER_MIRROHINT_F                   113
    //2F
    #define TRAINER_MIRROHINT2_A                  114
    #define TRAINER_MIRROHINT2_B                  115
    #define TRAINER_MIRROHINT2_C                  116
    #define TRAINER_MIRROHINT2_D                  117
    #define TRAINER_MIRROHINT2_E                  118
    #define TRAINER_MIRROHINT2_F                  119
    #define TRAINER_MIRROHINT2_G                  120

    //Mirroh Peak
    #define TRAINER_MIRROHPEAK_A                  121
    #define TRAINER_MIRROHPEAK_B                  122
    #define TRAINER_MIRROHPEAK_C                  123
    #define TRAINER_MIRROHPEAK_D                  124
    #define TRAINER_MIRROHPEAK_E                  125
    #define TRAINER_MIRROHPEAK_MOXIE              126

    //Winterlily Hollow Gym
    #define TRAINER_WINTERLILY_HOLLOW_GYM_A       127
    #define TRAINER_WINTERLILY_HOLLOW_GYM_B       128
    #define TRAINER_WINTERLILY_HOLLOW_GYM_C       129
    #define TRAINER_WINTERLILY_HOLLOW_GYM_D       130
    #define TRAINER_WINTERLILY_HOLLOW_GYM_E       131
    #define TRAINER_WINTERLILY_HOLLOW_GYM_F       132
    #define TRAINER_WINTERLILY_HOLLOW_GYM_LEADER  133


    //Pelluca Gym
    #define TRAINER_PELLUCA_CITY_GYM_A            134
    #define TRAINER_PELLUCA_CITY_GYM_B            135
    #define TRAINER_PELLUCA_CITY_GYM_C            136
    #define TRAINER_PELLUCA_CITY_GYM_D            137
    #define TRAINER_PELLUCA_CITY_GYM_E            138
    #define TRAINER_PELLUCA_CITY_GYM_F            139
    #define TRAINER_PELLUCA_CITY_GYM_G            140
    #define TRAINER_PELLUCA_CITY_GYM_H            141
    #define TRAINER_PELLUCA_CITY_GYM_I            142
    #define TRAINER_PELLUCA_CITY_GYM_LEADER       143

//Route 3 Extended
#define TRAINER_ROUTE3_EXT_A                         144
#define TRAINER_ROUTE3_EXT_B                         145
#define TRAINER_ROUTE3_EXT_C                         146

//Pelluca
#define TRAINER_PELLUCA_QWILSQUAD_A                  147
#define TRAINER_PELLUCA_QWILSQUAD_B                  148
#define TRAINER_PELLUCA_QWILSQUAD_BOSS               149
#define TRAINER_PELLUCA_DETECTIVE                    150

//Route 8
#define TRAINER_ROUTE8_A                             151
#define TRAINER_ROUTE8_B                             152
#define TRAINER_ROUTE8_C                             153
#define TRAINER_ROUTE8_D                             154
#define TRAINER_ROUTE8_E                             155
#define TRAINER_ROUTE8_F                             156

//Rivetshore Quarry
#define TRAINER_RIVETSHORE_GYM_A                     157
#define TRAINER_RIVETSHORE_GYM_B                     158
#define TRAINER_RIVETSHORE_GYM_C                     159
#define TRAINER_RIVETSHORE_GYM_D                     160
#define TRAINER_RIVETSHORE_GYM_E                     161
#define TRAINER_SSELEGANT_A                     162
#define TRAINER_SSELEGANT_B                     163
#define TRAINER_SSELEGANT_INGER                     164
#define TRAINER_SSELEGANT_ARIANA                     165
#define TRAINER_SSELEGANT_JANIA                     166
#define TRAINER_RIVETSHORE_GYM_LEADER                167

//Ivy River
#define TRAINER_IVY_RIVER_A                 168
#define TRAINER_IVY_RIVER_B                 169
#define TRAINER_IVY_RIVER_C                 170
#define TRAINER_IVY_RIVER_D                 171

//Uncharted Island
#define TRAINER_UNCHARTED_ISLAND_GRUNT_A    172
#define TRAINER_UNCHARTED_ISLAND_GRUNT_B    173
#define TRAINER_UNCHARTED_ISLAND_GRUNT_C    174
#define TRAINER_UNCHARTED_ISLAND_GRUNT_D    175
#define TRAINER_UNCHARTED_ISLAND_MOXIE      176
#define TRAINER_UNCHARTED_ISLAND_MELEA      177
#define TRAINER_UNCHARTED_ISLAND_RUE        178

//Route 1 Stronger
#define TRAINER_ROUTE1_STRONG_A             179
#define TRAINER_ROUTE1_STRONG_B             180
#define TRAINER_ROUTE1_STRONG_C             181

//Victory Road
#define TRAINER_VICTORY_ROAD_A              182
#define TRAINER_VICTORY_ROAD_B              183
#define TRAINER_VICTORY_ROAD_C              184
#define TRAINER_VICTORY_ROAD_D              185
#define TRAINER_VICTORY_ROAD_E              186
#define TRAINER_VICTORY_ROAD_F              187
#define TRAINER_VICTORY_ROAD_G              188
#define TRAINER_VICTORY_ROAD_H              189
#define TRAINER_VICTORY_ROAD_I              190
#define TRAINER_VICTORY_ROAD_J              191
#define TRAINER_VICTORY_ROAD_K              192
#define TRAINER_VICTORY_ROAD_L              193
#define TRAINER_VICTORY_ROAD_M              194
#define TRAINER_VICTORY_ROAD_N              195
#define TRAINER_VICTORY_ROAD_O              196

//Championship
#define TRAINER_CHAMPIONSHIP_A              197
#define TRAINER_CHAMPIONSHIP_B              198
#define TRAINER_CHAMPIONSHIP_C              199
#define TRAINER_CHAMPIONSHIP_D              200
#define TRAINER_CHAMPIONSHIP_E              201
#define TRAINER_CHAMPIONSHIP_F              202


//past champions
#define TRAINER_AXLE                        203
#define TRAINER_JACE                        204
#define TRAINER_KEEGAN                      205
#define TRAINER_BERNIE_1                    206




///FIRST 5 PLAYERS WHO BEAT THE GAME
#define TRAINER_PLAYER_SENTRY               207
#define TRAINER_PLAYER_EDEN                 208
#define TRAINER_PLAYER_GOZLIAK              209
#define TRAINER_PLAYER_SHERRY               210
#define TRAINER_PLAYER_MIKE                 211

//Route 7
#define TRAINER_ROUTE7_A                    212
#define TRAINER_ROUTE7_B                    213
#define TRAINER_ROUTE7_C                    214
#define TRAINER_ROUTE7_D                    215
#define TRAINER_ETHAN_1                     216
#define TRAINER_AUTUMN                      217
#define TRAINER_TRAVIS                      218
#define TRAINER_ETHAN_2                     219
#define TRAINER_ETHAN_3                     220
#define TRAINER_ETHAN_4                     221
#define TRAINER_ETHAN_5                     222
#define TRAINER_BRENT                       223
#define TRAINER_DONALD                      224
#define TRAINER_TAYLOR                      225
#define TRAINER_CHAMPIONSHIP_FREY_1                   226
#define TRAINER_DEREK                       227
#define TRAINER_CHAMPIONSHIP_FREY_2                   228
#define TRAINER_CHAMPIONSHIP_FREY_3                   229
#define TRAINER_CHAMPIONSHIP_FREY_4                   230
#define TRAINER_CHAMPIONSHIP_FREY_5                   231
#define TRAINER_EDWARD                      232
#define TRAINER_PRESTON                     233
#define TRAINER_VIRGIL                      234
#define TRAINER_BLAKE                       235
#define TRAINER_WILLIAM                     236
#define TRAINER_JOSHUA                      237
#define TRAINER_CAMERON_1                   238
#define TRAINER_CAMERON_2                   239
#define TRAINER_CAMERON_3                   240
#define TRAINER_CAMERON_4                   241
#define TRAINER_CAMERON_5                   242
#define TRAINER_JACLYN                      243
#define TRAINER_HANNAH                      244
#define TRAINER_SAMANTHA                    245
#define TRAINER_MAURA                       246
#define TRAINER_KAYLA                       247
#define TRAINER_ALEXIS                      248
#define TRAINER_UNCHARTED_ISLAND_GRUNT_AI_1                     249
#define TRAINER_UNCHARTED_ISLAND_GRUNT_AI_2                     250
#define TRAINER_UNCHARTED_ISLAND_GRUNT_AI_3                     251
#define TRAINER_UNCHARTED_ISLAND_GRUNT_AI_4                     252
#define TRAINER_UNCHARTED_ISLAND_GRUNT_AI_5                     253
#define TRAINER_WALTER_1                    254
#define TRAINER_MICAH                       255
#define TRAINER_THOMAS                      256
#define TRAINER_WALTER_2                    257
#define TRAINER_WALTER_3                    258
#define TRAINER_WALTER_4                    259
#define TRAINER_WALTER_5                    260
#define TRAINER_SIDNEY                      261
#define TRAINER_PHOEBE                      262
#define TRAINER_GLACIA                      263
#define TRAINER_DRAKE                       264
#define TRAINER_ROXANNE_1                   265
#define TRAINER_BRAWLY_1                    266
#define TRAINER_WATTSON_1                   267
#define TRAINER_FLANNERY_1                  268
#define TRAINER_NORMAN_1                    269
#define TRAINER_WINONA_1                    270
#define TRAINER_TATE_AND_LIZA_1             271
#define TRAINER_JUAN_1                      272
#define TRAINER_JERRY_1                     273
#define TRAINER_TED                         274
#define TRAINER_PAUL                        275
#define TRAINER_JERRY_2                     276
#define TRAINER_JERRY_3                     277
#define TRAINER_JERRY_4                     278
#define TRAINER_JERRY_5                     279
#define TRAINER_KAREN_1                     280
#define TRAINER_GEORGIA                     281
#define TRAINER_KAREN_2                     282
#define TRAINER_KAREN_3                     283
#define TRAINER_KAREN_4                     284
#define TRAINER_KAREN_5                     285
#define TRAINER_KATE_AND_JOY                286
#define TRAINER_ANNA_AND_MEG_1              287
#define TRAINER_ANNA_AND_MEG_2              288
#define TRAINER_ANNA_AND_MEG_3              289
#define TRAINER_ANNA_AND_MEG_4              290
#define TRAINER_ANNA_AND_MEG_5              291
#define TRAINER_VICTOR                      292
#define TRAINER_MIGUEL_1                    293
#define TRAINER_COLTON                      294
#define TRAINER_MIGUEL_2                    295
#define TRAINER_MIGUEL_3                    296
#define TRAINER_MIGUEL_4                    297
#define TRAINER_MIGUEL_5                    298
#define TRAINER_VICTORIA                    299
#define TRAINER_VANESSA                     300
#define TRAINER_BETHANY                     301
#define TRAINER_ISABEL_1                    302
#define TRAINER_ISABEL_2                    303
#define TRAINER_ISABEL_3                    304
#define TRAINER_ISABEL_4                    305
#define TRAINER_ISABEL_5                    306
#define TRAINER_TIMOTHY_1                   307
#define TRAINER_TIMOTHY_2                   308
#define TRAINER_TIMOTHY_3                   309
#define TRAINER_TIMOTHY_4                   310
#define TRAINER_TIMOTHY_5                   311
#define TRAINER_VICKY                       312
#define TRAINER_SHELBY_1                    313
#define TRAINER_SHELBY_2                    314
#define TRAINER_SHELBY_3                    315
#define TRAINER_SHELBY_4                    316
#define TRAINER_SHELBY_5                    317
#define TRAINER_CALVIN_1                    318
#define TRAINER_BILLY                       319
#define TRAINER_JOSH                        320
#define TRAINER_TOMMY                       321
#define TRAINER_JOEY                        322
#define TRAINER_BEN                         323
#define TRAINER_QUINCY                      324
#define TRAINER_KATELYNN                    325
#define TRAINER_JAYLEN                      326
#define TRAINER_DILLON                      327
#define TRAINER_CALVIN_2                    328
#define TRAINER_CALVIN_3                    329
#define TRAINER_CALVIN_4                    330
#define TRAINER_CALVIN_5                    331
#define TRAINER_EDDIE                       332
#define TRAINER_ALLEN                       333
#define TRAINER_TIMMY                       334
#define TRAINER_WALLACE                     335
#define TRAINER_ANDREW                      336
#define TRAINER_IVAN                        337
#define TRAINER_CLAUDE                      338
#define TRAINER_ELLIOT_1                    339
#define TRAINER_NED                         340
#define TRAINER_DALE                        341
#define TRAINER_NOLAN                       342
#define TRAINER_BARNY                       343
#define TRAINER_WADE                        344
#define TRAINER_CARTER                      345
#define TRAINER_ELLIOT_2                    346
#define TRAINER_ELLIOT_3                    347
#define TRAINER_ELLIOT_4                    348
#define TRAINER_ELLIOT_5                    349
#define TRAINER_RONALD                      350
#define TRAINER_JACOB                       351
#define TRAINER_ANTHONY                     352
#define TRAINER_BENJAMIN_1                  353
#define TRAINER_BENJAMIN_2                  354
#define TRAINER_BENJAMIN_3                  355
#define TRAINER_BENJAMIN_4                  356
#define TRAINER_BENJAMIN_5                  357
#define TRAINER_ABIGAIL_1                   358
#define TRAINER_JASMINE                     359
#define TRAINER_ABIGAIL_2                   360
#define TRAINER_ABIGAIL_3                   361
#define TRAINER_ABIGAIL_4                   362
#define TRAINER_ABIGAIL_5                   363
#define TRAINER_DYLAN_1                     364
#define TRAINER_DYLAN_2                     365
#define TRAINER_DYLAN_3                     366
#define TRAINER_DYLAN_4                     367
#define TRAINER_DYLAN_5                     368
#define TRAINER_MARIA_1                     369
#define TRAINER_MARIA_2                     370
#define TRAINER_MARIA_3                     371
#define TRAINER_MARIA_4                     372
#define TRAINER_MARIA_5                     373
#define TRAINER_CAMDEN                      374
#define TRAINER_DEMETRIUS                   375
#define TRAINER_ISAIAH_1                    376
#define TRAINER_PABLO_1                     377
#define TRAINER_CHASE                       378
#define TRAINER_ISAIAH_2                    379
#define TRAINER_ISAIAH_3                    380
#define TRAINER_ISAIAH_4                    381
#define TRAINER_ISAIAH_5                    382
#define TRAINER_ISOBEL                      383
#define TRAINER_DONNY                       384
#define TRAINER_TALIA                       385
#define TRAINER_KATELYN_1                   386
#define TRAINER_ALLISON                     387
#define TRAINER_KATELYN_2                   388
#define TRAINER_KATELYN_3                   389
#define TRAINER_KATELYN_4                   390
#define TRAINER_KATELYN_5                   391
#define TRAINER_NICOLAS_1                   392
#define TRAINER_NICOLAS_2                   393
#define TRAINER_NICOLAS_3                   394
#define TRAINER_NICOLAS_4                   395
#define TRAINER_NICOLAS_5                   396
#define TRAINER_AARON                       397
#define TRAINER_PERRY                       398
#define TRAINER_HUGH                        399
#define TRAINER_PHIL                        400
#define TRAINER_JARED                       401
#define TRAINER_HUMBERTO                    402
#define TRAINER_PRESLEY                     403
#define TRAINER_EDWARDO                     404
#define TRAINER_COLIN                       405
#define TRAINER_ROBERT_1                    406
#define TRAINER_BENNY                       407
#define TRAINER_CHESTER                     408
#define TRAINER_ROBERT_2                    409
#define TRAINER_ROBERT_3                    410
#define TRAINER_ROBERT_4                    411
#define TRAINER_ROBERT_5                    412
#define TRAINER_ALEX                        413
#define TRAINER_BECK                        414
#define TRAINER_YASU                        415
#define TRAINER_TAKASHI                     416
#define TRAINER_DIANNE                      417
#define TRAINER_JANI                        418
#define TRAINER_LAO_1                       419
#define TRAINER_LUNG                        420
#define TRAINER_LAO_2                       421
#define TRAINER_LAO_3                       422
#define TRAINER_LAO_4                       423
#define TRAINER_LAO_5                       424
#define TRAINER_JOCELYN                     425
#define TRAINER_LAURA                       426
#define TRAINER_CYNDY_1                     427
#define TRAINER_CORA                        428
#define TRAINER_PAULA                       429
#define TRAINER_CYNDY_2                     430
#define TRAINER_CYNDY_3                     431
#define TRAINER_CYNDY_4                     432
#define TRAINER_CYNDY_5                     433
#define TRAINER_MADELINE_1                  434
#define TRAINER_CLARISSA                    435
#define TRAINER_ANGELICA                    436
#define TRAINER_MADELINE_2                  437
#define TRAINER_MADELINE_3                  438
#define TRAINER_MADELINE_4                  439
#define TRAINER_MADELINE_5                  440
#define TRAINER_BEVERLY                     441
#define TRAINER_IMANI                       442
#define TRAINER_KYLA                        443
#define TRAINER_DENISE                      444
#define TRAINER_BETH                        445
#define TRAINER_TARA                        446
#define TRAINER_MISSY                       447
#define TRAINER_ALICE                       448
#define TRAINER_JENNY_1                     449
#define TRAINER_GRACE                       450
#define TRAINER_TANYA                       451
#define TRAINER_SHARON                      452
#define TRAINER_NIKKI                       453
#define TRAINER_BRENDA                      454
#define TRAINER_KATIE                       455
#define TRAINER_SUSIE                       456
#define TRAINER_KARA                        457
#define TRAINER_DANA                        458
#define TRAINER_SIENNA                      459
#define TRAINER_DEBRA                       460
#define TRAINER_LINDA                       461
#define TRAINER_KAYLEE                      462
#define TRAINER_LAUREL                      463
#define TRAINER_CARLEE                      464
#define TRAINER_JENNY_2                     465
#define TRAINER_JENNY_3                     466
#define TRAINER_JENNY_4                     467
#define TRAINER_JENNY_5                     468
#define TRAINER_HEIDI                       469
#define TRAINER_BECKY                       470
#define TRAINER_CAROL                       471
#define TRAINER_NANCY                       472
#define TRAINER_MARTHA                      473
#define TRAINER_DIANA_1                     474
#define TRAINER_CEDRIC                      475
#define TRAINER_IRENE                       476
#define TRAINER_DIANA_2                     477
#define TRAINER_DIANA_3                     478
#define TRAINER_DIANA_4                     479
#define TRAINER_DIANA_5                     480
#define TRAINER_AMY_AND_LIV_1               481
#define TRAINER_AMY_AND_LIV_2               482
#define TRAINER_GINA_AND_MIA_1              483
#define TRAINER_MIU_AND_YUKI                484
#define TRAINER_AMY_AND_LIV_3               485
#define TRAINER_GINA_AND_MIA_2              486
#define TRAINER_AMY_AND_LIV_4               487
#define TRAINER_AMY_AND_LIV_5               488
#define TRAINER_AMY_AND_LIV_6               489
#define TRAINER_HUEY                        490
#define TRAINER_EDMOND                      491
#define TRAINER_ERNEST_1                    492
#define TRAINER_DWAYNE                      493
#define TRAINER_PHILLIP                     494
#define TRAINER_LEONARD                     495
#define TRAINER_DUNCAN                      496
#define TRAINER_ERNEST_2                    497
#define TRAINER_ERNEST_3                    498
#define TRAINER_ERNEST_4                    499
#define TRAINER_ERNEST_5                    500
#define TRAINER_ELI                         501
#define TRAINER_ANNIKA                      502
#define TRAINER_JAZMYN                      503
#define TRAINER_JONAS                       504
#define TRAINER_KAYLEY                      505
#define TRAINER_AURON                       506
#define TRAINER_KELVIN                      507
#define TRAINER_MARLEY                      508
#define TRAINER_REYNA                       509
#define TRAINER_HUDSON                      510
#define TRAINER_CONOR                       511
#define TRAINER_EDWIN_1                     512
#define TRAINER_HECTOR                      513
#define TRAINER_TABITHA_MOSSDEEP            514
#define TRAINER_EDWIN_2                     515
#define TRAINER_EDWIN_3                     516
#define TRAINER_EDWIN_4                     517
#define TRAINER_EDWIN_5                     518
#define TRAINER_WALLY_VR_1                  519
#define TRAINER_BRENDAN_ROUTE_103_MUDKIP    520
#define TRAINER_BRENDAN_ROUTE_110_MUDKIP    521
#define TRAINER_BRENDAN_ROUTE_119_MUDKIP    522
#define TRAINER_BRENDAN_ROUTE_103_TREECKO   523
#define TRAINER_BRENDAN_ROUTE_110_TREECKO   524
#define TRAINER_BRENDAN_ROUTE_119_TREECKO   525
#define TRAINER_BRENDAN_ROUTE_103_TORCHIC   526
#define TRAINER_BRENDAN_ROUTE_110_TORCHIC   527
#define TRAINER_BRENDAN_ROUTE_119_TORCHIC   528
#define TRAINER_MAY_ROUTE_103_MUDKIP        529
#define TRAINER_MAY_ROUTE_110_MUDKIP        530
#define TRAINER_MAY_ROUTE_119_MUDKIP        531
#define TRAINER_MAY_ROUTE_103_TREECKO       532
#define TRAINER_MAY_ROUTE_110_TREECKO       533
#define TRAINER_MAY_ROUTE_119_TREECKO       534
#define TRAINER_MAY_ROUTE_103_TORCHIC       535
#define TRAINER_MAY_ROUTE_110_TORCHIC       536
#define TRAINER_MAY_ROUTE_119_TORCHIC       537
#define TRAINER_ISAAC_1                     538
#define TRAINER_DAVIS                       539
#define TRAINER_MITCHELL                    540
#define TRAINER_ISAAC_2                     541
#define TRAINER_ISAAC_3                     542
#define TRAINER_ISAAC_4                     543
#define TRAINER_ISAAC_5                     544
#define TRAINER_LYDIA_1                     545
#define TRAINER_HALLE                       546
#define TRAINER_GARRISON                    547
#define TRAINER_LYDIA_2                     548
#define TRAINER_LYDIA_3                     549
#define TRAINER_LYDIA_4                     550
#define TRAINER_LYDIA_5                     551
#define TRAINER_UNCHARTED_ISLAND_GRUNT_ASON_1                   552
#define TRAINER_LORENZO                     553
#define TRAINER_SEBASTIAN                   554
#define TRAINER_UNCHARTED_ISLAND_GRUNT_ASON_2                   555
#define TRAINER_UNCHARTED_ISLAND_GRUNT_ASON_3                   556
#define TRAINER_UNCHARTED_ISLAND_GRUNT_ASON_4                   557
#define TRAINER_UNCHARTED_ISLAND_GRUNT_ASON_5                   558
#define TRAINER_CATHERINE_1                 559
#define TRAINER_JENNA                       560
#define TRAINER_SOPHIA                      561
#define TRAINER_CATHERINE_2                 562
#define TRAINER_CATHERINE_3                 563
#define TRAINER_CATHERINE_4                 564
#define TRAINER_CATHERINE_5                 565
#define TRAINER_JULIO                       566
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_5     567
#define TRAINER_GRUNT_UNUSED                568
#define TRAINER_GRUNT_MT_PYRE_4             569
#define TRAINER_GRUNT_JAGGED_PASS           570
#define TRAINER_MARC                        571
#define TRAINER_BRENDEN                     572
#define TRAINER_LILITH                      573
#define TRAINER_CRISTIAN                    574
#define TRAINER_SYLVIA                      575
#define TRAINER_LEONARDO                    576
#define TRAINER_ATHENA                      577
#define TRAINER_HARRISON                    578
#define TRAINER_GRUNT_MT_CHIMNEY_2          579
#define TRAINER_CLARENCE                    580
#define TRAINER_TERRY                       581
#define TRAINER_NATE                        582
#define TRAINER_KATHLEEN                    583
#define TRAINER_CLIFFORD                    584
#define TRAINER_NICHOLAS                    585
#define TRAINER_GRUNT_SPACE_CENTER_3        586
#define TRAINER_GRUNT_SPACE_CENTER_4        587
#define TRAINER_GRUNT_SPACE_CENTER_5        588
#define TRAINER_GRUNT_SPACE_CENTER_6        589
#define TRAINER_GRUNT_SPACE_CENTER_7        590
#define TRAINER_MACEY                       591
#define TRAINER_BRENDAN_RUSTBORO_TREECKO    592
#define TRAINER_BRENDAN_RUSTBORO_MUDKIP     593
#define TRAINER_PAXTON                      594
#define TRAINER_ISABELLA                    595
#define TRAINER_GRUNT_WEATHER_INST_5        596
#define TRAINER_TABITHA_MT_CHIMNEY          597
#define TRAINER_JONATHAN                    598
#define TRAINER_BRENDAN_RUSTBORO_TORCHIC    599
#define TRAINER_MAY_RUSTBORO_MUDKIP         600
#define TRAINER_MAXIE_MAGMA_HIDEOUT         601
#define TRAINER_MAXIE_MT_CHIMNEY            602
#define TRAINER_TIANA                       603
#define TRAINER_HALEY_1                     604
#define TRAINER_JANICE                      605
#define TRAINER_VIVI                        606
#define TRAINER_HALEY_2                     607
#define TRAINER_HALEY_3                     608
#define TRAINER_HALEY_4                     609
#define TRAINER_HALEY_5                     610
#define TRAINER_SALLY                       611
#define TRAINER_ROBIN                       612
#define TRAINER_ANDREA                      613
#define TRAINER_CRISSY                      614
#define TRAINER_RICK                        615
#define TRAINER_LYLE                        616
#define TRAINER_JOSE                        617
#define TRAINER_DOUG                        618
#define TRAINER_GREG                        619
#define TRAINER_KENT                        620
#define TRAINER_JAMES_1                     621
#define TRAINER_JAMES_2                     622
#define TRAINER_JAMES_3                     623
#define TRAINER_JAMES_4                     624
#define TRAINER_JAMES_5                     625
#define TRAINER_BRICE                       626
#define TRAINER_TRENT_1                     627
#define TRAINER_LENNY                       628
#define TRAINER_LUCAS_1                     629
#define TRAINER_ALAN                        630
#define TRAINER_CLARK                       631
#define TRAINER_ERIC                        632
#define TRAINER_LUCAS_2                     633
#define TRAINER_MIKE_1                      634
#define TRAINER_MIKE_2                      635
#define TRAINER_TRENT_2                     636
#define TRAINER_TRENT_3                     637
#define TRAINER_TRENT_4                     638
#define TRAINER_TRENT_5                     639
#define TRAINER_DEZ_AND_LUKE                640
#define TRAINER_LEA_AND_JED                 641
#define TRAINER_KIRA_AND_DAN_1              642
#define TRAINER_KIRA_AND_DAN_2              643
#define TRAINER_KIRA_AND_DAN_3              644
#define TRAINER_KIRA_AND_DAN_4              645
#define TRAINER_KIRA_AND_DAN_5              646
#define TRAINER_JOHANNA                     647
#define TRAINER_GERALD                      648
#define TRAINER_VIVIAN                      649
#define TRAINER_DANIELLE                    650
#define TRAINER_HIDEO                       651
#define TRAINER_KEIGO                       652
#define TRAINER_RILEY                       653
#define TRAINER_FLINT                       654
#define TRAINER_ASHLEY                      655
#define TRAINER_WALLY_MAUVILLE              656
#define TRAINER_WALLY_VR_2                  657
#define TRAINER_WALLY_VR_3                  658
#define TRAINER_WALLY_VR_4                  659
#define TRAINER_WALLY_VR_5                  660
#define TRAINER_BRENDAN_LILYCOVE_MUDKIP     661
#define TRAINER_BRENDAN_LILYCOVE_TREECKO    662
#define TRAINER_BRENDAN_LILYCOVE_TORCHIC    663
#define TRAINER_MAY_LILYCOVE_MUDKIP         664
#define TRAINER_MAY_LILYCOVE_TREECKO        665
#define TRAINER_MAY_LILYCOVE_TORCHIC        666
#define TRAINER_JONAH                       667
#define TRAINER_HENRY                       668
#define TRAINER_ROGER                       669
#define TRAINER_ALEXA                       670
#define TRAINER_RUBEN                       671
#define TRAINER_KOJI_1                      672
#define TRAINER_WAYNE                       673
#define TRAINER_AIDAN                       674
#define TRAINER_REED                        675
#define TRAINER_TISHA                       676
#define TRAINER_TORI_AND_TIA                677
#define TRAINER_KIM_AND_IRIS                678
#define TRAINER_TYRA_AND_IVY                679
#define TRAINER_MEL_AND_PAUL                680
#define TRAINER_JOHN_AND_JAY_1              681
#define TRAINER_JOHN_AND_JAY_2              682
#define TRAINER_JOHN_AND_JAY_3              683
#define TRAINER_JOHN_AND_JAY_4              684
#define TRAINER_JOHN_AND_JAY_5              685
#define TRAINER_RELI_AND_IAN                686
#define TRAINER_LILA_AND_ROY_1              687
#define TRAINER_LILA_AND_ROY_2              688
#define TRAINER_LILA_AND_ROY_3              689
#define TRAINER_LILA_AND_ROY_4              690
#define TRAINER_LILA_AND_ROY_5              691
#define TRAINER_LISA_AND_RAY                692
#define TRAINER_CHRIS                       693
#define TRAINER_DAWSON                      694
#define TRAINER_SARAH                       695
#define TRAINER_DARIAN                      696
#define TRAINER_HAILEY                      697
#define TRAINER_CHANDLER                    698
#define TRAINER_KALEB                       699
#define TRAINER_JOSEPH                      700
#define TRAINER_ALYSSA                      701
#define TRAINER_MARCOS                      702
#define TRAINER_RHETT                       703
#define TRAINER_TYRON                       704
#define TRAINER_CELINA                      705
#define TRAINER_BIANCA                      706
#define TRAINER_HAYDEN                      707
#define TRAINER_SOPHIE                      708
#define TRAINER_COBY                        709
#define TRAINER_LAWRENCE                    710
#define TRAINER_WYATT                       711
#define TRAINER_ANGELINA                    712
#define TRAINER_KAI                         713
#define TRAINER_CHARLOTTE                   714
#define TRAINER_DEANDRE                     715
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1       716
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2       717
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3       718
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4       719
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5       720
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6       721
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7       722
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8       723
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9       724
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10      725
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11      726
#define TRAINER_GRUNT_MAGMA_HIDEOUT_12      727
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13      728
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14      729
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15      730
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16      731
#define TRAINER_TABITHA_MAGMA_HIDEOUT       732
#define TRAINER_DARCY                       733
#define TRAINER_MAXIE_MOSSDEEP              734
#define TRAINER_PETE                        735
#define TRAINER_ISABELLE                    736
#define TRAINER_ANDRES_1                    737
#define TRAINER_JOSUE                       738
#define TRAINER_CAMRON                      739
#define TRAINER_CORY_1                      740
#define TRAINER_CAROLINA                    741
#define TRAINER_ELIJAH                      742
#define TRAINER_CELIA                       743
#define TRAINER_BRYAN                       744
#define TRAINER_BRANDEN                     745
#define TRAINER_BRYANT                      746
#define TRAINER_SHAYLA                      747
#define TRAINER_KYRA                        748
#define TRAINER_JAIDEN                      749
#define TRAINER_ALIX                        750
#define TRAINER_HELENE                      751
#define TRAINER_MARLENE                     752
#define TRAINER_DEVAN                       753
#define TRAINER_JOHNSON                     754
#define TRAINER_MELINA                      755
#define TRAINER_BRANDI                      756
#define TRAINER_AISHA                       757
#define TRAINER_MAKAYLA                     758
#define TRAINER_FABIAN                      759
#define TRAINER_DAYTON                      760
#define TRAINER_RACHEL                      761
#define TRAINER_LEONEL                      762
#define TRAINER_CALLIE                      763
#define TRAINER_CALE                        764
#define TRAINER_MYLES                       765
#define TRAINER_PAT                         766
#define TRAINER_CRISTIN_1                   767
#define TRAINER_MAY_RUSTBORO_TREECKO        768
#define TRAINER_MAY_RUSTBORO_TORCHIC        769
#define TRAINER_ROXANNE_2                   770
#define TRAINER_ROXANNE_3                   771
#define TRAINER_ROXANNE_4                   772
#define TRAINER_ROXANNE_5                   773
#define TRAINER_BRAWLY_2                    774
#define TRAINER_BRAWLY_3                    775
#define TRAINER_BRAWLY_4                    776
#define TRAINER_BRAWLY_5                    777
#define TRAINER_WATTSON_2                   778
#define TRAINER_WATTSON_3                   779
#define TRAINER_WATTSON_4                   780
#define TRAINER_WATTSON_5                   781
#define TRAINER_FLANNERY_2                  782
#define TRAINER_FLANNERY_3                  783
#define TRAINER_FLANNERY_4                  784
#define TRAINER_FLANNERY_5                  785
#define TRAINER_NORMAN_2                    786
#define TRAINER_NORMAN_3                    787
#define TRAINER_NORMAN_4                    788
#define TRAINER_NORMAN_5                    789
#define TRAINER_WINONA_2                    790
#define TRAINER_WINONA_3                    791
#define TRAINER_WINONA_4                    792
#define TRAINER_WINONA_5                    793
#define TRAINER_TATE_AND_LIZA_2             794
#define TRAINER_TATE_AND_LIZA_3             795
#define TRAINER_TATE_AND_LIZA_4             796
#define TRAINER_TATE_AND_LIZA_5             797
#define TRAINER_JUAN_2                      798
#define TRAINER_JUAN_3                      799
#define TRAINER_JUAN_4                      800
#define TRAINER_JUAN_5                      801
#define TRAINER_ANGELO                      802
#define TRAINER_DARIUS                      803
#define TRAINER_STEVEN                      804
#define TRAINER_ANABEL                      805
#define TRAINER_TUCKER                      806
#define TRAINER_SPENSER                     807
#define TRAINER_GRETA                       808
#define TRAINER_NOLAND                      809
#define TRAINER_LUCY                        810
#define TRAINER_BRANDON                     811
#define TRAINER_ANDRES_2                    812
#define TRAINER_ANDRES_3                    813
#define TRAINER_ANDRES_4                    814
#define TRAINER_ANDRES_5                    815
#define TRAINER_CORY_2                      816
#define TRAINER_CORY_3                      817
#define TRAINER_CORY_4                      818
#define TRAINER_CORY_5                      819
#define TRAINER_PABLO_2                     820
#define TRAINER_PABLO_3                     821
#define TRAINER_PABLO_4                     822
#define TRAINER_PABLO_5                     823
#define TRAINER_KOJI_2                      824
#define TRAINER_KOJI_3                      825
#define TRAINER_KOJI_4                      826
#define TRAINER_KOJI_5                      827
#define TRAINER_CRISTIN_2                   828
#define TRAINER_CRISTIN_3                   829
#define TRAINER_CRISTIN_4                   830
#define TRAINER_CRISTIN_5                   831
#define TRAINER_FERNANDO_2                  832
#define TRAINER_FERNANDO_3                  833
#define TRAINER_FERNANDO_4                  834
#define TRAINER_FERNANDO_5                  835
#define TRAINER_SAWYER_2                    836
#define TRAINER_SAWYER_3                    837
#define TRAINER_SAWYER_4                    838
#define TRAINER_SAWYER_5                    839
#define TRAINER_GABRIELLE_2                 840
#define TRAINER_GABRIELLE_3                 841
#define TRAINER_GABRIELLE_4                 842
#define TRAINER_GABRIELLE_5                 843
#define TRAINER_THALIA_2                    844
#define TRAINER_THALIA_3                    845
#define TRAINER_THALIA_4                    846
#define TRAINER_THALIA_5                    847
#define TRAINER_MARIELA                     848
#define TRAINER_ALVARO                      849
#define TRAINER_EVERETT                     850
#define TRAINER_RED                         851
#define TRAINER_LEAF                        852
#define TRAINER_BRENDAN_PLACEHOLDER         853
#define TRAINER_MAY_PLACEHOLDER             854

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT                      855
#define MAX_TRAINERS_COUNT                  864
#define TRAINER_PARTNER(partner)           (MAX_TRAINERS_COUNT + partner)

#endif  // GUARD_CONSTANTS_OPPONENTS_H
