gText_PreBirch1::
	.string "This is a non-profit game. If you paid\n"
	.string "for it, please get your money back!\n"
	.string "\n"	
	.string "The mGBA emulator is recommended.\n"
	.string "\n"
	.string "Documentation for the game is available\n"		
	.string "online. If you get stuck, look it up!\p"	
	.string "$"
	
gText_PreBirch2::
	.string "For advanced players:\n"	
	.string "This game has no EVs. Natures and IVs\n"
	.string "can be changed via story progression.\n"
	.string "\n"
	.string "Difficulty can be set in the options.\n"	
	.string "Hardcore nuzlockers can talk to Mom\n"	
	.string "to acess quality-of-life features.\p"		
	.string "$"

gText_PreBirch3::
	.string "You are about to enter a living,\n"
	.string "breathing world with people and Pokémon.\n"
	.string "Take your time and explore every corner.\n"
	.string "Undertake your journey and grow with\n"
	.string "your trusted partners.\n"
	.string "\n"	
	.string "Are you ready for your adventure?\p"
	.string "$"
	
gText_Birch_Welcome::
	.string "TENEBRIS LABORATORY\n"
	.string "LETTER OF APPOINTMENT\p"
	.string "Congratulations, candidate! You have\n"
	.string "been selected as a Research Associate\l"
	.string "in the Tenebris Laboratory.\p"
	.string "MESSAGE FROM PROFESSOR TENEBRIS\n"
	.string "Welcome young researcher!\p"
	.string "I am Professor Tenebris, the resident\n"
	.string "Pokémon Prof. of the Cormoria region\l"
	.string "and head of the Tenebris Laboratory!\p"
	.string "We reviewed your application and while\n"
	.string "your resume was...lacking, I believe in\l"
	.string "inner potential, not words on a page!\p"
	.string "ABOUT THE LABORATORY\p"	
	.string "$"

gText_Birch_Pokemon::
	.string "ABOUT THE LABORATORY\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "Pokémon and humans have co-existed\n"
	.string "since the dawn of civilisation.\p"
	.string "Yet, we know so very little of our\n"
	.string "friends and aides.\p"
	.string "Pokémon Professors all over the world\n"
	.string "such as myself spend their time\p"
	.string "studying the biology, habits, and\n"
	.string "traits of the many Pokémon species.\p"
	.string "Here in my lab, we specialise in Pokémon\n"
	.string "psychology and their subconscious.\p"
	.string "What goes on in their minds? Where\n"
	.string "does their power and energy come from?\p"
	.string "That's what we do.\p"
	.string "Shall we proceed with your onboarding\n"
	.string "as a new employee at the lab?\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Please fill out this employee form:\p"
	.string "$"	

gText_Birch_BoyOrGirl::
	.string "Please submit a photograph of\n"
	.string "yourself for identification."
	.string "$"	

gText_Birch_WhatsYourName::
	.string "By signing below, you agree to accept\n"
	.string "the position of Research Associate."
	.string "$"

gText_Birch_SoItsPlayer::
	.string "Confirm signature: {PLAYER}?"
	.string "$"	

gText_Birch_YourePlayer::
	.string "Congratulations!\p"
	.string "I look forward to meeting\n"
	.string "you in the lab next week.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "FIRST DAY PROCEDURES:\p"
	.string "1. New researchers are to receive a\n" 
	.string "Pokémon companion on the first day.\p"
	.string "Our standard guidelines offer you\n"
	.string "the choice of one of the following:\l" 
	.string "{COLOR RED}Torchic{COLOR DARK_GRAY}, {COLOR GREEN}Chikorita{COLOR DARK_GRAY}, or {COLOR BLUE}Oshawott{COLOR DARK_GRAY}.\p"
	.string "{COLOR DARK_GRAY}2. You are expected to be punctual.\n"
	.string "Tardiness is not acceptable.\p"
	.string "3. We have sent a welcome package.\n"
	.string "Please carry this with you. In case\l"	
	.string "you have not yet received it, please\l"
	.string "inform us as soon as possible.\p"
	.string "Warmly,\n"
	.string "Professor Tenebris.\p"
	.string "$"



