gText_Birch_Welcome::
	.string "TENEBRIS LABORATORY\n"
	.string "LETTER OF APPOINTMENT\p"
	.string "Congratulations candidate!\p"
	.string "You have been selected as a\n"
	.string "RESEARCH ASSOCIATE at the\p"
	.string "Tenebris Laboratory in\n"
	.string "CARABRUE TOWN.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "MESSAGE FROM THE PROF”\p"
	.string "Welcome young researcher!\p"
	.string "I am PROFESSOR TENEBRIS,\n"
	.string "the POKéMON Professor of the\p"
	.string "Cormoria region and the head of\n"
	.string "the TENEBRIS LABORATORY!\p"
	.string "We reviewed your application\n"
	.string "and while your resume was...lacking,\n"
	.string "I believe in inner potential,\n"
	.string "not words on a page!\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "POKéMON and humans have co-existed\n"
	.string "since the dawn of civilisation.\p"
	.string "Yet, we know so very little of our\n"
	.string "friends and aides.\p"
	.string "POKéMON Professors all over the world\n"
	.string "such as muyself spend their time\p"
	.string "studying the biology, habits, and\n"
	.string "traits of the many POKéMON species.\p"
	.string "Here in my lab, we specialise in\n"
	.string "POKéMON psychology and subconscious.\p"
	.string "What goes on in their minds? Where\n"
	.string "does their power and energy come from?\p"
	.string "That's what we do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Please fill out this\n"
	.string "employee form.\p"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "To accept this offer letter\n"
	.string "please sign below.\p"

gText_Birch_SoItsPlayer::
	.string "Confirm signature: {PLAYER}?$"

gText_Birch_YourePlayer::
	.string "Congratulations!\p"
	.string "I look forward to meeting\n"
	.string "you in the lab next week.\n"
	.string "$"

gText_Birch_AreYouReady::
	.string "ADDENDUM:\p"
	.string "We have couriered you a\n"
	.string "Welcome Package.\p"
	.string "Please bring it with you\n"
	.string "on your first day.\p"
	.string "Best Regards,\n"
	.string "PROFESSOR TENEBRIS.\p"
	.string "$"
