gText_WouldYouLikeToRestYourPkmn::
	.string "Hello, and welcome to\n"
	.string "the POKéMON CENTER.\p"
	.string "We restore your tired POKéMON\n"
	.string "to full health.\p"
	.string "Would you like to rest your POKéMON?$"

gText_IllTakeYourPkmn::
	.string "Welcome to the Pokemon Center!\n"
	.string "Allow me to heal your POKéMON.$"

gText_RestoredPkmnToFullHealth::
	.string "Thank you for waiting.\p"
	.string "We've restored your POKéMON\n"
	.string "to full health.$"

gText_WeHopeToSeeYouAgain::
	.string "We hope to see you again!$"

gText_WelcomeCutShort::
	.string "Hello, and welcome to\n"
	.string "the POKéMON CENTER.\p"
	.string "We restore your tired POKéMON\n"
	.string "to full health.\p"
	.string "Would you like to…$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first TRAINER I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your POKéMON!$"

gText_YouWantTheUsual::
	.string "I'm delighted to see you, {PLAYER}!\n"
	.string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2::
	.string "Welcome to the Pokemon Center!\n"
	.string "Allow me to heal your POKéMON.$"

gText_ThankYouForWaiting::
	.string "Thank you for waiting.$"

gText_WeHopeToSeeYouAgain2::
	.string "We hope to see you again!$"


gText_TakeHealPass::
	.string "Please take this HEAL PASS. You can\n"
	.string "trade it in with any Nurse Joy outside\p"
	.string "a POKéMON CENTER to heal your POKéMON.$"

gTextExplainHealPass::
	.string "Trainer, is this your first time at a\n"
	.string "POKéMON CENTER?\p"
	.string "Then I have good news - we have a special\n"
	.string "promotion running right now!\p"
	.string "Each Trainer that heals in any POKéMON\n"
	.string "CENTER can receive upto one HEAL PASS.\p"
	.string "Trade it in with any Nurse Joy outside\n"
	.string "a POKéMON CENTER to heal your POKéMON.\p"
	.string "But you can only have one HEAL PASS\n"
	.string "at a time. Once you have traded your\p"
	.string "HEAL PASS in, please come back to any\n"
	.string "POKéMON CENTER to receive a new one!$"


