gText_WouldYouLikeToRestYourPkmn::
	.string "Hello, and welcome to\n"
	.string "the Pokémon Center.\p"
	.string "We restore your tired Pokémon\n"
	.string "to full health.\p"
	.string "Would you like to rest your Pokémon?$"

gText_IllTakeYourPkmn::
	.string "Welcome to the Pokemon Center!\n"
	.string "Allow me to heal your Pokémon.$"

gText_RestoredPkmnToFullHealth::
	.string "We've restored your Pokémon\n"
	.string "to full health.$"

gText_WeHopeToSeeYouAgain::
	.string "We hope to see you again!$"

gText_WelcomeCutShort::
	.string "Hello, and welcome to\n"
	.string "the Pokémon Center.\p"
	.string "We restore your tired Pokémon\n"
	.string "to full health.\p"
	.string "Would you like to…$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first TRAINER I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your Pokémon!$"

gText_YouWantTheUsual::
	.string "I'm delighted to see you, {PLAYER}!\n"
	.string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2::
	.string "Welcome to the Pokemon Center!\n"
	.string "Allow me to heal your Pokémon.$"

gText_ThankYouForWaiting::
	.string "Thank you for waiting.\n"
	.string "We hope to see you again!$"	

gText_WeHopeToSeeYouAgain2::
	.string "We hope to see you again!$"

gText_TakeHealPass::
	.string "I'll give you a new Heal Pass too!$"

gText_ExplainHealPass::
	.string "Trainer, is this your first time at a\n"
	.string "Pokémon Center?\p"
	.string "Then I have good news - we have a\n"
	.string "special promotion running right now!\p"
	.string "Each Trainer that heals at a Pokémon\n"
	.string "Center can receive up to one Heal Pass.\p"
	.string "Trade it in with any Nurse Joy outside\n"
	.string "a Pokémon Center to heal your Pokémon.\p"
	.string "But you can only have one Heal Pass\n"
	.string "at a time. Once you've used up your\l"
	.string "Heal Pass, please come back to any\l"
	.string "Pokémon Center to receive a new one!$"


