Route7_MapScripts::
	.byte 0


Route7_Trainer_A::
# 8 "data//maps/Route7/scripts.pory"
	trainerbattle_single TRAINER_ROUTE7_A, Route7_Trainer_A_Text_0, Route7_Trainer_A_Text_1
# 9 "data//maps/Route7/scripts.pory"
	msgbox Route7_Trainer_A_Text_2, MSGBOX_NPC
	end


Route7_Trainer_B::
# 13 "data//maps/Route7/scripts.pory"
	trainerbattle_single TRAINER_ROUTE7_B, Route7_Trainer_B_Text_0, Route7_Trainer_B_Text_1
# 14 "data//maps/Route7/scripts.pory"
	msgbox Route7_Trainer_B_Text_2, MSGBOX_NPC
	end


Route7_Trainer_C::
# 18 "data//maps/Route7/scripts.pory"
	trainerbattle_single TRAINER_ROUTE7_C, Route7_Trainer_C_Text_0, Route7_Trainer_C_Text_1
# 19 "data//maps/Route7/scripts.pory"
	msgbox Route7_Trainer_C_Text_2, MSGBOX_NPC
	end


Route7_Trainer_D::
# 23 "data//maps/Route7/scripts.pory"
	trainerbattle_single TRAINER_ROUTE7_D, Route7_Trainer_D_Text_0, Route7_Trainer_D_Text_1
# 24 "data//maps/Route7/scripts.pory"
	msgbox Route7_Trainer_D_Text_2, MSGBOX_NPC
	end


Route7_NPC1::
# 35 "data//maps/Route7/scripts.pory"
	msgbox Route7_NPC1_Text_0, MSGBOX_NPC
	end


Route7_NPC2::
# 39 "data//maps/Route7/scripts.pory"
	msgbox Route7_NPC2_Text_0, MSGBOX_NPC
	end


Route7_NPC3::
# 43 "data//maps/Route7/scripts.pory"
	msgbox Route7_NPC3_Text_0, MSGBOX_NPC
	end


Route7_Trainer_A_Text_0:
# 8 "data//maps/Route7/scripts.pory"
	.string "I worked double shifts at the Pelluca\n"
	.string "Restaurant all week.\p"
	.string "Time to let out some steam!$"

Route7_Trainer_A_Text_1:
# 8 "data//maps/Route7/scripts.pory"
	.string "You ruined my day off!$"

Route7_Trainer_A_Text_2:
# 9 "data//maps/Route7/scripts.pory"
	.string "What? Can't a waitress have a day off?$"

Route7_Trainer_B_Text_0:
# 13 "data//maps/Route7/scripts.pory"
	.string "My parents want me become an actress,\n"
	.string "so I practice battling here in secret!$"

Route7_Trainer_B_Text_1:
# 13 "data//maps/Route7/scripts.pory"
	.string "Maybe I should be an actress!$"

Route7_Trainer_B_Text_2:
# 14 "data//maps/Route7/scripts.pory"
	.string "I know anybody would want to be me with\n"
	.string "my looks, but I only care for battling!$"

Route7_Trainer_C_Text_0:
# 18 "data//maps/Route7/scripts.pory"
	.string "My big brother and I are going camping!\n"
	.string "Don't get in our way!$"

Route7_Trainer_C_Text_1:
# 18 "data//maps/Route7/scripts.pory"
	.string "I wanted to go camping!$"

Route7_Trainer_C_Text_2:
# 19 "data//maps/Route7/scripts.pory"
	.string "My brother travels all around Cormoria.\n"
	.string "He's so cool!$"

Route7_Trainer_D_Text_0:
# 23 "data//maps/Route7/scripts.pory"
	.string "Every year I take my sister camping.\n"
	.string "A battle will get us going!$"

Route7_Trainer_D_Text_1:
# 23 "data//maps/Route7/scripts.pory"
	.string "That got us going alright!$"

Route7_Trainer_D_Text_2:
# 24 "data//maps/Route7/scripts.pory"
	.string "I don't get to be home much. That's why\n"
	.string "I cherish the time I get with my sister.$"

Route7_NPC1_Text_0:
# 35 "data//maps/Route7/scripts.pory"
	.string "I was scared of going to Pelluca City\n"
	.string "because I heard about the Qwilsquad.\l"
	.string "Are they gone?$"

Route7_NPC2_Text_0:
# 39 "data//maps/Route7/scripts.pory"
	.string "They're closing the gym at Mirroh Base\n"
	.string "Camp! I should hurry if I want my badge.$"

Route7_NPC3_Text_0:
# 43 "data//maps/Route7/scripts.pory"
	.string "Do you think the cable car attendant\n"
	.string "will go out with me?$"
