WhiteSign_CarabrueTown_Main::
# 6 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_CarabrueTown_Main_Text_0, MSGBOX_SIGN
	end


WhiteSign_CarabrueTown_TenebrisLab::
# 11 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_CarabrueTown_TenebrisLab_Text_0, MSGBOX_SIGN
	end


WhiteSign_Route1_NextToCarabrue::
# 18 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Route1_NextToCarabrue_Text_0, MSGBOX_SIGN
	end


WoodSign_Route1_Middle::
# 24 "data//scripts/customscripts_signs.pory"
	speakername WoodSign_Route1_Middle_Text_0
# 25 "data//scripts/customscripts_signs.pory"
	msgbox WoodSign_Route1_Middle_Text_1, MSGBOX_SIGN
	end


WhiteSign_Route1_NextToFennilahl::
# 30 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Route1_NextToFennilahl_Text_0, MSGBOX_SIGN
	end


WhiteSign_FennilahlTown_Main::
# 37 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_FennilahlTown_Main_Text_0, MSGBOX_SIGN
	end


WhiteSign_FennilahlTown_TowardsRoute2::
# 42 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_FennilahlTown_TowardsRoute2_Text_0, MSGBOX_SIGN
	end


WhiteSign_FennilahlTown_TowardsRoute3::
# 47 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_FennilahlTown_TowardsRoute3_Text_0, MSGBOX_SIGN
	end


WoodSign_FennilahlTown_Nicknaming::
# 52 "data//scripts/customscripts_signs.pory"
	speakername WoodSign_Route1_Middle_Text_0
# 53 "data//scripts/customscripts_signs.pory"
	msgbox WoodSign_FennilahlTown_Nicknaming_Text_0, MSGBOX_SIGN
	end


WoodSign_Fennilahl_Pokedex::
# 58 "data//scripts/customscripts_signs.pory"
	speakername WoodSign_Route1_Middle_Text_0
# 59 "data//scripts/customscripts_signs.pory"
	msgbox WoodSign_Fennilahl_Pokedex_Text_0, MSGBOX_SIGN
	end


WhiteSign_Route3_TowardsFennilahl::
# 68 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Route3_TowardsFennilahl_Text_0, MSGBOX_SIGN
	end


WhiteSign_Route3_VineRiverUnderpass::
# 73 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Route3_VineRiverUnderpass_Text_0, MSGBOX_SIGN
	end


WhiteSign_Route3_TowardsGastree::
# 78 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Route3_TowardsGastree_Text_0, MSGBOX_SIGN
	end


WhiteSign_GastreeCity_Main::
# 87 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_GastreeCity_Main_Text_0, MSGBOX_SIGN
	end


WhiteSign_GastreeCity_TeaHouse::
# 92 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_GastreeCity_TeaHouse_Text_0, MSGBOX_SIGN
	end


WhiteSign_GastreeCity_Gym::
# 97 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_GastreeCity_Gym_Text_0, MSGBOX_SIGN
	end


WoodSign_GastreeCity_GetStuck::
# 102 "data//scripts/customscripts_signs.pory"
	msgbox WoodSign_GastreeCity_GetStuck_Text_0, MSGBOX_SIGN
	end


WhiteSign_Route4_TowardsGastree::
# 110 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Route4_TowardsGastree_Text_0, MSGBOX_SIGN
	end


WhiteSign_Route4_TowardsCeramBaseCamp::
# 115 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Route4_TowardsCeramBaseCamp_Text_0, MSGBOX_SIGN
	end


WoodSign_Route4_HM::
# 119 "data//scripts/customscripts_signs.pory"
	speakername WoodSign_Route1_Middle_Text_0
# 120 "data//scripts/customscripts_signs.pory"
	msgbox WoodSign_Route4_HM_Text_0, MSGBOX_SIGN
	end


WhiteSign_CeramBaseCamp_Main::
# 129 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_CeramBaseCamp_Main_Text_0, MSGBOX_SIGN
	end


WhiteSign_CeramBaseCamp_UpToMtCeram::
# 135 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_CeramBaseCamp_UpToMtCeram_Text_0, MSGBOX_SIGN
	end


WhiteSign_CeramBaseCamp_SupplyDepot::
# 141 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_CeramBaseCamp_SupplyDepot_Text_0, MSGBOX_SIGN
	end


WhiteSign_CeramBaseCamp_Gym::
# 146 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_CeramBaseCamp_Gym_Text_0, MSGBOX_SIGN
	end


WoodSign_CeramBaseCamp_Something::
# 150 "data//scripts/customscripts_signs.pory"
	msgbox WoodSign_CeramBaseCamp_Something_Text_0, MSGBOX_SIGN
	end


WoodSign_MtCeram_Warning::
# 160 "data//scripts/customscripts_signs.pory"
	msgbox WoodSign_MtCeram_Warning_Text_0, MSGBOX_SIGN
	end


WhiteSign_GalecrestCity_Main::
# 171 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_GalecrestCity_Main_Text_0, MSGBOX_SIGN
	end


WhiteSign_GalecrestCity_Garden::
# 177 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_GalecrestCity_Garden_Text_0, MSGBOX_SIGN
	end


WhiteSign_GalecrestCity_GameCorner::
# 183 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_GalecrestCity_GameCorner_Text_0, MSGBOX_SIGN
	end


WhiteSign_GalecrestCity_DetectiveAcademy::
# 188 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_GalecrestCity_DetectiveAcademy_Text_0, MSGBOX_SIGN
	end


WhiteSign_Galecrest_Gym::
# 193 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Galecrest_Gym_Text_0, MSGBOX_SIGN
	end


WhiteSign_Route5_ToGalecrest::
# 198 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Route5_ToGalecrest_Text_0, MSGBOX_SIGN
	end


WhiteSign_Route5_ToSilversun::
# 203 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Route5_ToSilversun_Text_0, MSGBOX_SIGN
	end


WhiteSign_Route5_Vilethorn::
# 208 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Route5_Vilethorn_Text_0, MSGBOX_SIGN
	end


WoodSign_SilversunCity_Artist1::
# 215 "data//scripts/customscripts_signs.pory"
	msgbox WoodSign_SilversunCity_Artist1_Text_0, MSGBOX_SIGN
	end


WoodSign_SilversunCity_Artist2::
# 220 "data//scripts/customscripts_signs.pory"
	msgbox WoodSign_SilversunCity_Artist2_Text_0, MSGBOX_SIGN
	end


WoodSign_SilversunCity_Artist3::
# 225 "data//scripts/customscripts_signs.pory"
	msgbox WoodSign_SilversunCity_Artist3_Text_0, MSGBOX_SIGN
	end


WhiteSign_SilversunCity_Main::
# 230 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_SilversunCity_Main_Text_0, MSGBOX_SIGN
	end


WhiteSign_SilversunCity_Theater::
# 235 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_SilversunCity_Theater_Text_0, MSGBOX_SIGN
	end


WhiteSign_SilversunCity_Orphanage::
# 240 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_SilversunCity_Orphanage_Text_0, MSGBOX_SIGN
	end


WhiteSign_SilversunCity_Sewers::
# 245 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_SilversunCity_Sewers_Text_0, MSGBOX_SIGN
	end


WhiteSign_SilversunCity_DrifblimTravels::
# 250 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_SilversunCity_DrifblimTravels_Text_0, MSGBOX_SIGN
	end


WhiteSign_SilversunCity_Gym::
# 255 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_SilversunCity_Gym_Text_0, MSGBOX_SIGN
	end


WhiteSign_HoyaRiverNorth::
# 262 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_HoyaRiverNorth_Text_0, MSGBOX_SIGN
	end


WhiteSign_HoyaRiverSouth::
# 267 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_HoyaRiverSouth_Text_0, MSGBOX_SIGN
	end


WhiteSign_Route6_ToSilversun::
# 272 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Route6_ToSilversun_Text_0, MSGBOX_SIGN
	end


WhiteSign_Route6_ToPelluca::
# 277 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Route6_ToPelluca_Text_0, MSGBOX_SIGN
	end


WhiteSign_Route6_RangerInstitute::
# 282 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Route6_RangerInstitute_Text_0, MSGBOX_SIGN
	end


WhiteSign_PellucaCity_Main::
# 290 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_PellucaCity_Main_Text_0, MSGBOX_SIGN
	end


WhiteSign_PellucaCity_MayorHouse::
# 295 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_PellucaCity_MayorHouse_Text_0, MSGBOX_SIGN
	end


WhiteSign_PellucaCity_Restaurant::
# 300 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_PellucaCity_Restaurant_Text_0, MSGBOX_SIGN
	end


WhiteSign_PellucaCity_GameCorner::
# 306 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_PellucaCity_GameCorner_Text_0, MSGBOX_SIGN
	end


WhiteSign_PellucaCity_Fishery::
# 311 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_PellucaCity_Fishery_Text_0
	end


WhiteSign_PellucaCity_ToCableCar::
# 316 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_PellucaCity_ToCableCar_Text_0, MSGBOX_SIGN
	end


WhiteSign_CableCar_ToMirroh::
# 322 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_CableCar_ToMirroh_Text_0, MSGBOX_SIGN
	end


WhiteSign_CableCar_ToPelluca::
# 326 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_CableCar_ToPelluca_Text_0, MSGBOX_SIGN
	end


WhiteSign_MirrohBaseCamp_Gym::
# 332 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_MirrohBaseCamp_Gym_Text_0, MSGBOX_SIGN
	end


WhiteSign_MirrohBaseCamp_Main::
# 337 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_MirrohBaseCamp_Main_Text_0, MSGBOX_SIGN
	end


WhiteSign_MirrohBaseCamp_Martha::
# 342 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_MirrohBaseCamp_Martha_Text_0, MSGBOX_SIGN
	end


WhiteSign_Route8_ToBaseCamp::
# 349 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Route8_ToBaseCamp_Text_0, MSGBOX_SIGN
	end


WhiteSign_Route8_ToMtMirroh::
# 353 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Route8_ToMtMirroh_Text_0, MSGBOX_SIGN
	end


WhiteSign_Route8_Dojo::
# 357 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Route8_Dojo_Text_0, MSGBOX_SIGN
	end


WhiteSign_MirrohPeak_ToMirrohInt::
# 365 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_MirrohPeak_ToMirrohInt_Text_0, MSGBOX_SIGN
	end


WhiteSign_MirrohPeak_ToWinterlilyHollow::
# 369 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_MirrohPeak_ToWinterlilyHollow_Text_0, MSGBOX_SIGN
	end


WhiteSign_IvyRiver_RangerInstitute::
# 381 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_IvyRiver_RangerInstitute_Text_0, MSGBOX_SIGN
	end


WhiteSign_IvyRiver_Main::
# 386 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_IvyRiver_Main_Text_0, MSGBOX_SIGN
	end


WhiteSign_Rivetshore_Main::
# 394 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Rivetshore_Main_Text_0, MSGBOX_SIGN
	end


WhiteSign_Rivetshore_Construction::
# 398 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Rivetshore_Construction_Text_0, MSGBOX_SIGN
	end


WhiteSign_Rivetshore_Quarry::
# 402 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Rivetshore_Quarry_Text_0, MSGBOX_SIGN
	end


WhiteSign_Rivetshore_Storage::
# 406 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Rivetshore_Storage_Text_0, MSGBOX_SIGN
	end


WhiteSign_Rivetshore_Harbor::
# 410 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Rivetshore_Harbor_Text_0, MSGBOX_SIGN
	end


WhiteSign_Rivetshore_Ranger::
# 414 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Rivetshore_Ranger_Text_0, MSGBOX_SIGN
	end


WhiteSign_VictoryRoad::
# 425 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_VictoryRoad_Text_0, MSGBOX_SIGN
	end


WhiteSign_VictoryCape_Main::
# 429 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_VictoryCape_Main_Text_0, MSGBOX_SIGN
	end


WhiteSign_VictoryCape_Hotel::
# 433 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_VictoryCape_Hotel_Text_0, MSGBOX_SIGN
	end


WhiteSign_VictoryCape_Mart::
# 437 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_VictoryCape_Mart_Text_0, MSGBOX_SIGN
	end


WhiteSign_VictoryCape_Venue::
# 441 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_VictoryCape_Venue_Text_0, MSGBOX_SIGN
	end


WhiteSign_CarabrueTown_Main_Text_0:
# 6 "data//scripts/customscripts_signs.pory"
	.string "Carabrue Town\n"
	.string "An idyllic hill station.$"

WhiteSign_CarabrueTown_TenebrisLab_Text_0:
# 11 "data//scripts/customscripts_signs.pory"
	.string "Tenebris Laboratory\n"
	.string "Pokémon psychology research hub.$"

WhiteSign_Route1_NextToCarabrue_Text_0:
# 18 "data//scripts/customscripts_signs.pory"
	.string "Route 1\n"
	.string "New beginnings!\p"
	.string "{LEFT_ARROW} Carabrue Town\n"
	.string "{UP_ARROW} Fennilahl Town$"

WoodSign_Route1_Middle_Text_0:
# 24 "data//scripts/customscripts_signs.pory"
	.string "Trainer Tips$"

WoodSign_Route1_Middle_Text_1:
# 25 "data//scripts/customscripts_signs.pory"
	.string "You can sometimes find hidden items\n"
	.string "in rocks and stuff!$"

WhiteSign_Route1_NextToFennilahl_Text_0:
# 30 "data//scripts/customscripts_signs.pory"
	.string "Route 1\n"
	.string "New beginnings!\p"
	.string "{RIGHT_ARROW} Fennilahl Town.\n"
	.string "{LEFT_ARROW} Carabrue Town.$"

WhiteSign_FennilahlTown_Main_Text_0:
# 37 "data//scripts/customscripts_signs.pory"
	.string "Fennilahl Town\n"
	.string "A calm, serene retirement home.$"

WhiteSign_FennilahlTown_TowardsRoute2_Text_0:
# 42 "data//scripts/customscripts_signs.pory"
	.string "{DOWN_ARROW}ROUTE 2\p"
	.string "{DOWN_ARROW}Starfall Caves.\n"
	.string "{RIGHT_ARROW}Vine River.$"

WhiteSign_FennilahlTown_TowardsRoute3_Text_0:
# 47 "data//scripts/customscripts_signs.pory"
	.string "{UP_ARROW} Underground Tunnel\n"
	.string "To Route 3 and Gastree City.$"

WoodSign_FennilahlTown_Nicknaming_Text_0:
# 53 "data//scripts/customscripts_signs.pory"
	.string "Press START to sort items in your bag!$"

WoodSign_Fennilahl_Pokedex_Text_0:
# 59 "data//scripts/customscripts_signs.pory"
	.string "Check your Pokédex to learn about\n"
	.string "evolution methods and movesets!$"

WhiteSign_Route3_TowardsFennilahl_Text_0:
# 68 "data//scripts/customscripts_signs.pory"
	.string "Route 3\n"
	.string "A journey through the hills!\p"
	.string "{UP_ARROW} Fennilahl Town.\n"
	.string "{RIGHT_ARROW} Gastree City.$"

WhiteSign_Route3_VineRiverUnderpass_Text_0:
# 73 "data//scripts/customscripts_signs.pory"
	.string "{UP_ARROW} Vine River Underpass.$"

WhiteSign_Route3_TowardsGastree_Text_0:
# 78 "data//scripts/customscripts_signs.pory"
	.string "Route 3\n"
	.string "A journey through the hills!\p"
	.string "{UP_ARROW} Gastree City.\n"
	.string "{LEFT_ARROW} Fennilahl Town.$"

WhiteSign_GastreeCity_Main_Text_0:
# 87 "data//scripts/customscripts_signs.pory"
	.string "Gastree City\n"
	.string "Where fall colors never fade.$"

WhiteSign_GastreeCity_TeaHouse_Text_0:
# 92 "data//scripts/customscripts_signs.pory"
	.string "Gastree Teahouse\n"
	.string "Fragrant teas and quiet moments.$"

WhiteSign_GastreeCity_Gym_Text_0:
# 97 "data//scripts/customscripts_signs.pory"
	.string "Gastree Gym\n"
	.string "Leader: Inger$"

WoodSign_GastreeCity_GetStuck_Text_0:
# 102 "data//scripts/customscripts_signs.pory"
	.string "If you get stuck, check your quests\n"
	.string "and talk to people!$"

WhiteSign_Route4_TowardsGastree_Text_0:
# 110 "data//scripts/customscripts_signs.pory"
	.string "Route 4\p"
	.string "{DOWN_ARROW} Gastree City.\n"
	.string "{UP_ARROW} Ceram Base Camp.$"

WhiteSign_Route4_TowardsCeramBaseCamp_Text_0:
# 115 "data//scripts/customscripts_signs.pory"
	.string "Route 4\p"
	.string "{UP_ARROW} Ceram Base Camp.\n"
	.string "{DOWN_ARROW} Gastree City.$"

WoodSign_Route4_HM_Text_0:
# 120 "data//scripts/customscripts_signs.pory"
	.string "Pokémon can use HMs without learning\n"
	.string "them! But you need enough badges.$"

WhiteSign_CeramBaseCamp_Main_Text_0:
# 129 "data//scripts/customscripts_signs.pory"
	.string "Ceram Base Camp\n"
	.string "Starting point for Mt. Ceram treks.$"

WhiteSign_CeramBaseCamp_UpToMtCeram_Text_0:
# 135 "data//scripts/customscripts_signs.pory"
	.string "{UP_ARROW} Mt. Ceram\n"
	.string "Supplies available at depot next door.$"

WhiteSign_CeramBaseCamp_SupplyDepot_Text_0:
# 141 "data//scripts/customscripts_signs.pory"
	.string "Supply Depot\n"
	.string "All your trekking needs!$"

WhiteSign_CeramBaseCamp_Gym_Text_0:
# 146 "data//scripts/customscripts_signs.pory"
	.string "Ceram Base Camp Gym and\n"
	.string "Management Office$"

WoodSign_CeramBaseCamp_Something_Text_0:
# 150 "data//scripts/customscripts_signs.pory"
	.string "TRAINER TIPS: You can relearn old\n"
	.string "moves via the Pokémon Summary Screen!$"

WoodSign_MtCeram_Warning_Text_0:
# 160 "data//scripts/customscripts_signs.pory"
	.string "TRAINER TIPS: If you jump this ledge,\n"
	.string "there's no way back! Make sure you're\l"
	.string "prepared for the trek.$"

WhiteSign_GalecrestCity_Main_Text_0:
# 171 "data//scripts/customscripts_signs.pory"
	.string "Galecrest City\n"
	.string "Where elegance meets ambition.$"

WhiteSign_GalecrestCity_Garden_Text_0:
# 177 "data//scripts/customscripts_signs.pory"
	.string "Galecrest Garden\n"
	.string "Please don't disturb the ROTOMS.$"

WhiteSign_GalecrestCity_GameCorner_Text_0:
# 183 "data//scripts/customscripts_signs.pory"
	.string "Galecrest Game Corner\n"
	.string "Minors are not allowed!$"

WhiteSign_GalecrestCity_DetectiveAcademy_Text_0:
# 188 "data//scripts/customscripts_signs.pory"
	.string "Detective Academy\n"
	.string "Where sharp minds are forged.$"

WhiteSign_Galecrest_Gym_Text_0:
# 193 "data//scripts/customscripts_signs.pory"
	.string "Galecrest Gym\p"
	.string "Managed by the Galecrest Academy\n"
	.string "Student Council.$"

WhiteSign_Route5_ToGalecrest_Text_0:
# 198 "data//scripts/customscripts_signs.pory"
	.string "Route 5\p"
	.string "{RIGHT_ARROW} Galecrest City.\n"
	.string "{LEFT_ARROW} Silversun City.$"

WhiteSign_Route5_ToSilversun_Text_0:
# 203 "data//scripts/customscripts_signs.pory"
	.string "Route 5\p"
	.string "{LEFT_ARROW} Silversun City.\n"
	.string "{RIGHT_ARROW} Galecrest City.$"

WhiteSign_Route5_Vilethorn_Text_0:
# 208 "data//scripts/customscripts_signs.pory"
	.string "{UP_ARROW}Vilethorn Woods\n"
	.string "Travelers beware!$"

WoodSign_SilversunCity_Artist1_Text_0:
# 215 "data//scripts/customscripts_signs.pory"
	.string "You are NOT to disturb the great\n"
	.string "Arsalan!$"

WoodSign_SilversunCity_Artist2_Text_0:
# 220 "data//scripts/customscripts_signs.pory"
	.string "Philistines keep OUT!$"

WoodSign_SilversunCity_Artist3_Text_0:
# 225 "data//scripts/customscripts_signs.pory"
	.string "Deliveries by the door please.$"

WhiteSign_SilversunCity_Main_Text_0:
# 230 "data//scripts/customscripts_signs.pory"
	.string "Silversun City\n"
	.string "The metropolis of the north.$"

WhiteSign_SilversunCity_Theater_Text_0:
# 235 "data//scripts/customscripts_signs.pory"
	.string "Silversun Theatre\n"
	.string "Prepare to be enthralled!\p"
	.string "Bookings close a day prior.\n"
	.string "No food and drinks allowed!$"

WhiteSign_SilversunCity_Orphanage_Text_0:
# 240 "data//scripts/customscripts_signs.pory"
	.string "Silversun Blind Orphanage\n"
	.string "Love can be seen by all.$"

WhiteSign_SilversunCity_Sewers_Text_0:
# 245 "data//scripts/customscripts_signs.pory"
	.string "Silversun Sewers\n"
	.string "Entry for authorised personnel only.$"

WhiteSign_SilversunCity_DrifblimTravels_Text_0:
# 250 "data//scripts/customscripts_signs.pory"
	.string "Drifblim Travels Pvt. Ltd.\n"
	.string "Affordable intercity rides!$"

WhiteSign_SilversunCity_Gym_Text_0:
# 255 "data//scripts/customscripts_signs.pory"
	.string "Silversun Gym\n"
	.string "Leader: Gloria.$"

WhiteSign_HoyaRiverNorth_Text_0:
# 262 "data//scripts/customscripts_signs.pory"
	.string "Hoya River North Crossin\n"
	.string "No swimming in these waters!\p"
	.string "{RIGHT_ARROW} Silversun City.\n"
	.string "{DOWN_ARROW} Route 6.$"

WhiteSign_HoyaRiverSouth_Text_0:
# 267 "data//scripts/customscripts_signs.pory"
	.string "Hoya River South Crossing\n"
	.string "No swimming in these waters!\p"
	.string "{LEFT_ARROW} Pelluca City.\n"
	.string "{RIGHT_ARROW} Route 6.$"

WhiteSign_Route6_ToSilversun_Text_0:
# 272 "data//scripts/customscripts_signs.pory"
	.string "Route 6\n"
	.string "Beware the marshes!\p"
	.string "{UP_ARROW} Silversun City.\n"
	.string "{DOWN_ARROW} Pelluca City.$"

WhiteSign_Route6_ToPelluca_Text_0:
# 277 "data//scripts/customscripts_signs.pory"
	.string "Route 6\n"
	.string "Beware the marshes!\p"
	.string "{LEFT_ARROW} Pelluca City.\n"
	.string "{RIGHT_ARROW} Silversun City.$"

WhiteSign_Route6_RangerInstitute_Text_0:
# 282 "data//scripts/customscripts_signs.pory"
	.string "The Pokémon Ranger Institute\n"
	.string "Route 6 Branch$"

WhiteSign_PellucaCity_Main_Text_0:
# 290 "data//scripts/customscripts_signs.pory"
	.string "Pelluca City\n"
	.string "Where rivers meet.$"

WhiteSign_PellucaCity_MayorHouse_Text_0:
# 295 "data//scripts/customscripts_signs.pory"
	.string "Mayor's House$"

WhiteSign_PellucaCity_Restaurant_Text_0:
# 300 "data//scripts/customscripts_signs.pory"
	.string "Pelluca Restauant\n"
	.string "Don't skip our apple tarts!$"

WhiteSign_PellucaCity_GameCorner_Text_0:
# 306 "data//scripts/customscripts_signs.pory"
	.string "Pelluca Game Corner\n"
	.string "Feeling lucky tonight?$"

WhiteSign_PellucaCity_Fishery_Text_0:
# 311 "data//scripts/customscripts_signs.pory"
	.string "It's old and hard to read...\p"
	.string "...lluca Fishery...\n"
	.string "...fish...upplies...tours!$"

WhiteSign_PellucaCity_ToCableCar_Text_0:
# 316 "data//scripts/customscripts_signs.pory"
	.string "{LEFT_ARROW} Mirroh Base Camp\n"
	.string "Please wear warm clothing!$"

WhiteSign_CableCar_ToMirroh_Text_0:
# 322 "data//scripts/customscripts_signs.pory"
	.string "Cable Car to Mirroh Base Camp$"

WhiteSign_CableCar_ToPelluca_Text_0:
# 326 "data//scripts/customscripts_signs.pory"
	.string "Cable Car to Pelluca City$"

WhiteSign_MirrohBaseCamp_Gym_Text_0:
# 332 "data//scripts/customscripts_signs.pory"
	.string "Mirroh Base Camp Gym\n"
	.string "NOW DECOMISSIONED.$"

WhiteSign_MirrohBaseCamp_Main_Text_0:
# 337 "data//scripts/customscripts_signs.pory"
	.string "Mirroh Base Camp\n"
	.string "Wrapped in the hush of snow.$"

WhiteSign_MirrohBaseCamp_Martha_Text_0:
# 342 "data//scripts/customscripts_signs.pory"
	.string "Graveyard Management\n"
	.string "Caretaker: Martha$"

WhiteSign_Route8_ToBaseCamp_Text_0:
# 349 "data//scripts/customscripts_signs.pory"
	.string "Mt. Mirroh\p"
	.string "{DOWN_ARROW} Mirroh Base Camp.\n"
	.string "{UP_ARROW} Mirroh Caverns.$"

WhiteSign_Route8_ToMtMirroh_Text_0:
# 353 "data//scripts/customscripts_signs.pory"
	.string "Mirroh Caverns\p"
	.string "{UP_ARROW} Winterlily Hollow.\n"
	.string "{DOWN_ARROW} Mirroh Base Camp.$"

WhiteSign_Route8_Dojo_Text_0:
# 357 "data//scripts/customscripts_signs.pory"
	.string "Garden Shop\n"
	.string "For all your gardening needs!$"

WhiteSign_MirrohPeak_ToMirrohInt_Text_0:
# 365 "data//scripts/customscripts_signs.pory"
	.string "Mirroh Caverns\p"
	.string "{LEFT_ARROW} Winterlily Hollow.$"

WhiteSign_MirrohPeak_ToWinterlilyHollow_Text_0:
# 369 "data//scripts/customscripts_signs.pory"
	.string "{UP_ARROW} Winterlily Hollow.{LEFT_ARROW} Mt. Mirroh Peak.$"

WhiteSign_IvyRiver_RangerInstitute_Text_0:
# 381 "data//scripts/customscripts_signs.pory"
	.string "The Pokémon Ranger Institute\n"
	.string "Ivy River Branch$"

WhiteSign_IvyRiver_Main_Text_0:
# 386 "data//scripts/customscripts_signs.pory"
	.string "Ivy River\n"
	.string "{UP_ARROW} Winterlily Hollow.{DOWN_ARROW} Pelluca City.$"

WhiteSign_Rivetshore_Main_Text_0:
# 394 "data//scripts/customscripts_signs.pory"
	.string "Rivetshore City$"

WhiteSign_Rivetshore_Construction_Text_0:
# 398 "data//scripts/customscripts_signs.pory"
	.string "Rivetshore Construction\n"
	.string "A legacy of strong foundations$"

WhiteSign_Rivetshore_Quarry_Text_0:
# 402 "data//scripts/customscripts_signs.pory"
	.string "Rivetshore Quarry$"

WhiteSign_Rivetshore_Storage_Text_0:
# 406 "data//scripts/customscripts_signs.pory"
	.string "Storage Bay\n"
	.string "No tresspassers allowed!$"

WhiteSign_Rivetshore_Harbor_Text_0:
# 410 "data//scripts/customscripts_signs.pory"
	.string "Rivetshore Harbor\n"
	.string "The biggest harbor in Cormoria!$"

WhiteSign_Rivetshore_Ranger_Text_0:
# 414 "data//scripts/customscripts_signs.pory"
	.string "The Pokémon Ranger Institute\n"
	.string "Rivetshore City Branch$"

WhiteSign_VictoryRoad_Text_0:
# 425 "data//scripts/customscripts_signs.pory"
	.string "Victory Road$"

WhiteSign_VictoryCape_Main_Text_0:
# 429 "data//scripts/customscripts_signs.pory"
	.string "Victory Cape\n"
	.string "The Cormoria Pokémon Championship$"

WhiteSign_VictoryCape_Hotel_Text_0:
# 433 "data//scripts/customscripts_signs.pory"
	.string "The Victory Cape Hotel$"

WhiteSign_VictoryCape_Mart_Text_0:
# 437 "data//scripts/customscripts_signs.pory"
	.string "Victory Cape Dept. Store$"

WhiteSign_VictoryCape_Venue_Text_0:
# 441 "data//scripts/customscripts_signs.pory"
	.string "Championship Stadium$"
