WhiteSign_CarabrueTown_Main::
# 6 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_CarabrueTown_Main_Text_0, MSGBOX_SIGN
	end


WhiteSign_CarabrueTown_TenebrisLab::
# 11 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_CarabrueTown_TenebrisLab_Text_0, MSGBOX_SIGN
	end


WhiteSign_Route1_NextToCarabrue::
# 18 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Route1_NextToCarabrue_Text_0, MSGBOX_SIGN
	end


WoodSign_Route1_Middle::
# 24 "data//scripts/customscripts_signs.pory"
	msgbox WoodSign_Route1_Middle_Text_0, MSGBOX_SIGN
	end


WhiteSign_Route1_NextToFennilahl::
# 29 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Route1_NextToFennilahl_Text_0, MSGBOX_SIGN
	end


WhiteSign_FennilahlTown_Main::
# 36 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_FennilahlTown_Main_Text_0, MSGBOX_SIGN
	end


WhiteSign_FennilahlTown_TowardsRoute2::
# 41 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_FennilahlTown_TowardsRoute2_Text_0, MSGBOX_SIGN
	end


WhiteSign_FennilahlTown_TowardsRoute3::
# 46 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_FennilahlTown_TowardsRoute3_Text_0, MSGBOX_SIGN
	end


WhiteSign_Route3_TowardsFennilahl::
# 57 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Route3_TowardsFennilahl_Text_0, MSGBOX_SIGN
	end


WhiteSign_Route3_VineRiverUnderpass::
# 62 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Route3_VineRiverUnderpass_Text_0, MSGBOX_SIGN
	end


WhiteSign_Route3_TowardsGastree::
# 67 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Route3_TowardsGastree_Text_0, MSGBOX_SIGN
	end


WhiteSign_GastreeCity_Main::
# 76 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_GastreeCity_Main_Text_0, MSGBOX_SIGN
	end


WhiteSign_GastreeCity_TeaHouse::
# 81 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_GastreeCity_TeaHouse_Text_0, MSGBOX_SIGN
	end


WhiteSign_GastreeCity_Gym::
# 86 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_GastreeCity_Gym_Text_0, MSGBOX_SIGN
	end


WhiteSign_Route4_TowardsGastree::
# 94 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Route4_TowardsGastree_Text_0, MSGBOX_SIGN
	end


WhiteSign_Route4_TowardsCeramBaseCamp::
# 99 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_Route4_TowardsCeramBaseCamp_Text_0, MSGBOX_SIGN
	end


WhiteSign_CeramBaseCamp_Main::
# 109 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_CeramBaseCamp_Main_Text_0, MSGBOX_SIGN
	end


WhiteSign_CeramBaseCamp_UpToMtCeram::
# 115 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_CeramBaseCamp_UpToMtCeram_Text_0, MSGBOX_SIGN
	end


WhiteSign_CeramBaseCamp_SupplyDepot::
# 121 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_CeramBaseCamp_SupplyDepot_Text_0, MSGBOX_SIGN
	end


WhiteSign_CeramBaseCamp_Gym::
# 126 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_CeramBaseCamp_Gym_Text_0, MSGBOX_SIGN
	end


WoodSign_MtCeram_Warning::
# 134 "data//scripts/customscripts_signs.pory"
	msgbox WoodSign_MtCeram_Warning_Text_0, MSGBOX_SIGN
	end


WhiteSign_GalecrestCity_Main::
# 145 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_GalecrestCity_Main_Text_0, MSGBOX_SIGN
	end


WhiteSign_GalecrestCity_Garden::
# 151 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_GalecrestCity_Garden_Text_0, MSGBOX_SIGN
	end


WhiteSign_GalecrestCity_DetectiveAcademy::
# 157 "data//scripts/customscripts_signs.pory"
	msgbox WhiteSign_GalecrestCity_DetectiveAcademy_Text_0, MSGBOX_SIGN
	end


WhiteSign_CarabrueTown_Main_Text_0:
# 6 "data//scripts/customscripts_signs.pory"
	.string "CARABRUE TOWN\n"
	.string "An idyllic hill station.$"

WhiteSign_CarabrueTown_TenebrisLab_Text_0:
# 11 "data//scripts/customscripts_signs.pory"
	.string "THE TENEBRIS LABORATORY\n"
	.string "Pokemon psychology research hub.$"

WhiteSign_Route1_NextToCarabrue_Text_0:
# 18 "data//scripts/customscripts_signs.pory"
	.string "ROUTE 1\p"
	.string "{LEFT_ARROW} CARABRUE TOWN\n"
	.string "{UP_ARROW} FENNILAHL TOWN$"

WoodSign_Route1_Middle_Text_0:
# 24 "data//scripts/customscripts_signs.pory"
	.string "You can sometimes find hidden items in\n"
	.string "rocks!$"

WhiteSign_Route1_NextToFennilahl_Text_0:
# 29 "data//scripts/customscripts_signs.pory"
	.string "ROUTE 1\p"
	.string "{RIGHT_ARROW} FENNILAHL TOWN\n"
	.string "{LEFT_ARROW} CARABRUE TOWN.$"

WhiteSign_FennilahlTown_Main_Text_0:
# 36 "data//scripts/customscripts_signs.pory"
	.string "FENNILAHL TOWN\n"
	.string "A calm, serene retirement home.$"

WhiteSign_FennilahlTown_TowardsRoute2_Text_0:
# 41 "data//scripts/customscripts_signs.pory"
	.string "{DOWN_ARROW}ROUTE 2\n"
	.string "Connecting to Vine River.$"

WhiteSign_FennilahlTown_TowardsRoute3_Text_0:
# 46 "data//scripts/customscripts_signs.pory"
	.string "{UP_ARROW} UNDERGROUND TUNNEL\n"
	.string "To ROUTE 3 and GASTREE CITY.$"

WhiteSign_Route3_TowardsFennilahl_Text_0:
# 57 "data//scripts/customscripts_signs.pory"
	.string "ROUTE 3\p"
	.string "{UP_ARROW} FENNILAHL TOWN\n"
	.string "{RIGHT_ARROW} GASTREE CITY.$"

WhiteSign_Route3_VineRiverUnderpass_Text_0:
# 62 "data//scripts/customscripts_signs.pory"
	.string "{UP_ARROW} VINE RIVER UNDERPASS.$"

WhiteSign_Route3_TowardsGastree_Text_0:
# 67 "data//scripts/customscripts_signs.pory"
	.string "ROUTE 3\p"
	.string "{UP_ARROW} GASTREE CITY.\n"
	.string "{LEFT_ARROW} FENNILAHL TOWN$"

WhiteSign_GastreeCity_Main_Text_0:
# 76 "data//scripts/customscripts_signs.pory"
	.string "GASTREE CITY\n"
	.string "Where fall colors never fade.$"

WhiteSign_GastreeCity_TeaHouse_Text_0:
# 81 "data//scripts/customscripts_signs.pory"
	.string "GASTREE TEAHOUSE\n"
	.string "Fragrant teas and quiet moments.$"

WhiteSign_GastreeCity_Gym_Text_0:
# 86 "data//scripts/customscripts_signs.pory"
	.string "GASTREE GYM\n"
	.string "Leader: INGER$"

WhiteSign_Route4_TowardsGastree_Text_0:
# 94 "data//scripts/customscripts_signs.pory"
	.string "ROUTE 4\p"
	.string "{DOWN_ARROW} GASTREE CITY.\n"
	.string "{UP_ARROW} CERAM BASE CAMP$"

WhiteSign_Route4_TowardsCeramBaseCamp_Text_0:
# 99 "data//scripts/customscripts_signs.pory"
	.string "ROUTE 4\p"
	.string "{UP_ARROW} CERAM BASE CAMP\n"
	.string "{DOWN_ARROW} GASTREE CITY.$"

WhiteSign_CeramBaseCamp_Main_Text_0:
# 109 "data//scripts/customscripts_signs.pory"
	.string "CERAM BASE CAMP\n"
	.string "Starting point for MT CERAM treks.$"

WhiteSign_CeramBaseCamp_UpToMtCeram_Text_0:
# 115 "data//scripts/customscripts_signs.pory"
	.string "{UP_ARROW} MT CERAM\n"
	.string "Supplies available at depot next door.$"

WhiteSign_CeramBaseCamp_SupplyDepot_Text_0:
# 121 "data//scripts/customscripts_signs.pory"
	.string "SUPPLY DEPOT\n"
	.string "All your trekking needs!$"

WhiteSign_CeramBaseCamp_Gym_Text_0:
# 126 "data//scripts/customscripts_signs.pory"
	.string "GASTREE GYM\n"
	.string "Leader: ARIAN$"

WoodSign_MtCeram_Warning_Text_0:
# 134 "data//scripts/customscripts_signs.pory"
	.string "WARNING: If you jump this ledge,\n"
	.string "there's no way back! Make sure you're\l"
	.string "prepared for the trek.$"

WhiteSign_GalecrestCity_Main_Text_0:
# 145 "data//scripts/customscripts_signs.pory"
	.string "GALECREST CITY\n"
	.string "Where elegance meets ambition.$"

WhiteSign_GalecrestCity_Garden_Text_0:
# 151 "data//scripts/customscripts_signs.pory"
	.string "GALECREST GARDEN\n"
	.string "Please don't disturb the ROTOMS.$"

WhiteSign_GalecrestCity_DetectiveAcademy_Text_0:
# 157 "data//scripts/customscripts_signs.pory"
	.string "DETECTIVE ACADEMY\n"
	.string "WWhere sharp minds are forged.$"
