Route3_MapScripts::
	.byte 0


Route1_TrainerBattle_Kim::
# 5 "data//maps/Route3/scripts.pory"
	trainerbattle_single TRAINER_ROUTE3_KIM, Route1_TrainerBattle_Kim_Text_0, Route1_TrainerBattle_Kim_Text_1
# 6 "data//maps/Route3/scripts.pory"
	msgbox Route1_TrainerBattle_Kim_Text_2
# 7 "data//maps/Route3/scripts.pory"
	release
	end


Route1_TrainerBattle_Ronnie::
# 14 "data//maps/Route3/scripts.pory"
	trainerbattle_single TRAINER_ROUTE3_RONNIE, Route1_TrainerBattle_Kim_Text_0, Route1_TrainerBattle_Kim_Text_1
# 15 "data//maps/Route3/scripts.pory"
	msgbox Route1_TrainerBattle_Kim_Text_2
# 16 "data//maps/Route3/scripts.pory"
	release
	end


Route1_TrainerBattle_Jana::
# 23 "data//maps/Route3/scripts.pory"
	trainerbattle_single TRAINER_ROUTE3_JANA, Route1_TrainerBattle_Kim_Text_0, Route1_TrainerBattle_Kim_Text_1
# 24 "data//maps/Route3/scripts.pory"
	msgbox Route1_TrainerBattle_Kim_Text_2
# 25 "data//maps/Route3/scripts.pory"
	release
	end


Route1_TrainerBattle_Chara::
# 32 "data//maps/Route3/scripts.pory"
	trainerbattle_single TRAINER_ROUTE3_CHARA, Route1_TrainerBattle_Kim_Text_0, Route1_TrainerBattle_Kim_Text_1
# 33 "data//maps/Route3/scripts.pory"
	msgbox Route1_TrainerBattle_Kim_Text_2
# 34 "data//maps/Route3/scripts.pory"
	release
	end


Route1_TrainerBattle_Kim_Text_0:
# 5 "data//maps/Route3/scripts.pory"
	.string "Sefe fefe$"

Route1_TrainerBattle_Kim_Text_1:
# 5 "data//maps/Route3/scripts.pory"
	.string "fefe fef efe err rr rrr$"

Route1_TrainerBattle_Kim_Text_2:
# 6 "data//maps/Route3/scripts.pory"
	.string "goo$"
