WinterlilyHollow_Houses_MapScripts::
	.byte 0


WinterlilyHollow_Houses_NPC1::
# 5 "data//maps/WinterlilyHollow_Houses/scripts.pory"
	msgbox WinterlilyHollow_Houses_NPC1_Text_0, MSGBOX_NPC
	end


WinterlilyHollow_Houses_Graveler::
# 9 "data//maps/WinterlilyHollow_Houses/scripts.pory"
	playmoncry SPECIES_GRAVELER_ALOLA, CRY_MODE_NORMAL
# 10 "data//maps/WinterlilyHollow_Houses/scripts.pory"
	msgbox WinterlilyHollow_Houses_NPC1_Text_0, MSGBOX_NPC
	end


WinterlilyHollow_Houses_NPC2::
# 16 "data//maps/WinterlilyHollow_Houses/scripts.pory"
	msgbox WinterlilyHollow_Houses_NPC1_Text_0, MSGBOX_NPC
	end


WinterlilyHollow_Houses_NPC3::
# 21 "data//maps/WinterlilyHollow_Houses/scripts.pory"
	msgbox WinterlilyHollow_Houses_NPC1_Text_0, MSGBOX_NPC
	end


WinterlilyHollow_Houses_NPC4::
# 26 "data//maps/WinterlilyHollow_Houses/scripts.pory"
	msgbox WinterlilyHollow_Houses_NPC1_Text_0, MSGBOX_NPC
	end


WinterlilyHollow_Houses_Carkol::
# 30 "data//maps/WinterlilyHollow_Houses/scripts.pory"
	playmoncry SPECIES_CARKOL, CRY_MODE_NORMAL
# 31 "data//maps/WinterlilyHollow_Houses/scripts.pory"
	msgbox WinterlilyHollow_Houses_NPC1_Text_0, MSGBOX_NPC
	end


WinterlilyHollow_Houses_NPC1_Text_0:
# 5 "data//maps/WinterlilyHollow_Houses/scripts.pory"
	.string "$"
