Route8_MapScripts::
	.byte 0


Route8_Trainer_A::
# 7 "data//maps/Route8/scripts.pory"
	trainerbattle_single TRAINER_ROUTE8_A, Route8_Trainer_A_Text_0, Route8_Trainer_A_Text_0
# 8 "data//maps/Route8/scripts.pory"
	msgbox Route8_Trainer_A_Text_0
# 9 "data//maps/Route8/scripts.pory"
	releaseall
	end


Route8_Trainer_B::
# 14 "data//maps/Route8/scripts.pory"
	trainerbattle_single TRAINER_ROUTE8_B, Route8_Trainer_A_Text_0, Route8_Trainer_A_Text_0
# 15 "data//maps/Route8/scripts.pory"
	msgbox Route8_Trainer_A_Text_0
# 16 "data//maps/Route8/scripts.pory"
	releaseall
	end


Route8_Trainer_C::
# 21 "data//maps/Route8/scripts.pory"
	trainerbattle_single TRAINER_ROUTE8_C, Route8_Trainer_A_Text_0, Route8_Trainer_A_Text_0
# 22 "data//maps/Route8/scripts.pory"
	msgbox Route8_Trainer_A_Text_0
# 23 "data//maps/Route8/scripts.pory"
	releaseall
	end


Route8_Trainer_D::
# 28 "data//maps/Route8/scripts.pory"
	trainerbattle_single TRAINER_ROUTE8_D, Route8_Trainer_A_Text_0, Route8_Trainer_A_Text_0
# 29 "data//maps/Route8/scripts.pory"
	msgbox Route8_Trainer_A_Text_0
# 30 "data//maps/Route8/scripts.pory"
	releaseall
	end


Route8_Trainer_E::
# 35 "data//maps/Route8/scripts.pory"
	trainerbattle_single TRAINER_ROUTE8_E, Route8_Trainer_A_Text_0, Route8_Trainer_A_Text_0
# 36 "data//maps/Route8/scripts.pory"
	msgbox Route8_Trainer_A_Text_0
# 37 "data//maps/Route8/scripts.pory"
	releaseall
	end


Route8_Trainer_A_Text_0:
# 7 "data//maps/Route8/scripts.pory"
	.string "$"
